### ISSUE TITLE
Can not server side render html of tip tap using laravel SSR

### ISSUE THREAD

**Issue by stetim94** [ueberdosis/tiptap#1397]
In the following ticket:
https://github.com/ueberdosis/tiptap/issues/821
this is mentioned:
The current implementation still needs a document, but I’m going to add JSDOM support 

and this is the error I get:
```
The command "/usr/bin/node /application/storage/app/ssr/69118be818c6f4103ba9177ae5b7d114.js" failed. Exit Code: 1(General error) Working directory: /application/public Output: ================ Error Output: ================ /application/storage/app/ssr/69118be818c6f4103ba9177ae5b7d114.js:27739 const res = document.querySelector(container); ^ ReferenceError: document is not defined at normalizeContainer (/application/storage/app/ssr/69118be818c6f4103ba9177ae5b7d114.js:27739:21) at Object.app.mount (/application/storage/app/ssr/69118be818c6f4103ba9177ae5b7d114.js:27697:27) at Module../resources/assets/js/app-client.js (/application/storage/app/ssr/69118be818c6f4103ba9177ae5b7d114.js:28413:5) at __webpack_require__ (/application/storage/app/ssr/69118be818c6f4103ba9177ae5b7d114.js:45628:42) at /application/storage/app/ssr/69118be818c6f4103ba9177ae5b7d114.js:45701:69 at /application/storage/app/ssr/69118be818c6f4103ba9177ae5b7d114.js:45714:3 at Object.<anonymous> (/application/storage/app/ssr/69118be818c6f4103ba9177ae5b7d114.js:45716:12) at Module._compile (internal/modules/cjs/loader.js:778:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10) at Module.load (internal/modules/cjs/loader.js:653:32) (View: /application/resources/views/test.blade.php) 
```
Is the JSDOM support already available? 

the vue component:
```
<template>
    <div>
      {{ output}}
    </div>
</template>

<script>
import {generateHTML} from "@tiptap/html";

export default {
    computed: {
      output() {
        const doc = {
          'type': 'document',
          'content': [{
            'type': 'paragraph',
            'attrs': {
              'align': 'left'
            },
            'content': [{
              'type': 'text',
              'text': 'My sample text'
            }]
          }]
        }

        return generateHTML(this.template.body, [
          Document,
          Text,
        ])
      },
    },
};
</script>
```
the blade view (using spatie package for ssr):
```<html>
<head>
    <title>My server side rendered app</title>
    <script defer src="{{ asset('assets/js/app-client.js') }}"></script>
</head>
<body>
    <div id="app">
        {!! ssr('assets/js/app-server.js')->render() !!}
    </div>
</body>
</html>
```
tiptap versions:
```
        "@tiptap/core": "^2.0.0-beta.73",
        "@tiptap/extension-document": "^2.0.0-beta.1",
        "@tiptap/extension-paragraph": "^2.0.0-beta.1",
        "@tiptap/html": "^2.0.0-beta.9",
        "@tiptap/starter-kit": "^2.0.0-beta.70",
        "@tiptap/vue-3": "^2.0.0-beta.40",
```
Hope this is enough information, if something is missing please let me know

**Comment by hanspagel** [comment]
Thanks for reporting! You pass only two extensions too `generateHTML`, that doesn’t look right. Your example JSON requires at least three extensions: `Document`, `Paragraph` and `Text`. Would you mind trying it with those three?

BTW, I’m working on a tiptap v2 compatible PHP package to render HTML.

**Comment by stetim94** [comment]
even without generateHTML the build does not succeed. Then I must have messed up something in the setup of server side rendering. I have must have suffered from tunnel vision yesterday. 

Thank you for your time and help, you have been really helpful. 

is there anywhere I can follow the progress on your tiptap v2 compatible PHP package?

**Comment by stetim94** [comment]
not a problem with tip-tap, closing issue.

**Comment by stetim94** [comment]
@hanspagel , sorry to revive this issue, but I am still struggling. Would you mind helping me? 

I got the SSR working with this package: https://github.com/cretueusebiu/laravel-nuxt

but this results in an error:
``` 
ERROR  Document is not defined                                                                                                                                                                                                                                                                                                                                  16:00:11

  at a.output (client/pages/tiptap.vue:30:0)
  at a.output (node_modules/vue/dist/vue.runtime.common.prod.js:6:29698)
  at a.render (client/pages/tiptap.vue)
  at a.t._render (node_modules/vue/dist/vue.runtime.common.prod.js:6:35273)
  at node_modules/vue-server-renderer/build.prod.js:1:70637
  at Yi (node_modules/vue-server-renderer/build.prod.js:1:67201)
  at io (node_modules/vue-server-renderer/build.prod.js:1:70613)
  at ro (node_modules/vue-server-renderer/build.prod.js:1:70244)
  at eo (node_modules/vue-server-renderer/build.prod.js:1:67491)
  at node_modules/vue-server-renderer/build.prod.js:1:70711
```
I need to generate a PDF based on the result of tip-tap, but sending the HTML from the front-end doesn't feel safe. What I a missing?

**Comment by hanspagel** [comment]
What’s you’re code? The error message looks like you used tiptap, but you need to use the utility package.

https://github.com/ueberdosis/tiptap/issues/1397#issue-907519958

https://www.tiptap.dev/api/utilities/html

**Comment by stetim94** [comment]
The utility package uses the same import:
```
<template>
  <pre><code>{{ output }}</code></pre>
</template>

<script>
// Option 1: Browser + server-side
import { generateHTML } from '@tiptap/html'
// Option 2: Browser-only (lightweight)
// import { generateHTML } from '@tiptap/core'
import Document from '@tiptap/extension-document'
import Paragraph from '@tiptap/extension-paragraph'
import Text from '@tiptap/extension-text'
import Bold from '@tiptap/extension-bold'

const json = {
  type: 'doc',
  content: [
    {
      type: 'paragraph',
      content: [
        {
          type: 'text',
          text: 'Example ',
        },
        {
          type: 'text',
          marks: [
            {
              type: 'bold',
            },
          ],
          text: 'Text',
        },
      ],
    },
  ],
}

export default {
  computed: {
    output() {
      return generateHTML(json, [
        Document,
        Paragraph,
        Text,
        Bold,
        // other extensions …
      ])
    },
  },
}
</script>
```
as the code I use:
```
<template>
  <div>
    {{ output }}
  </div>
</template>

<script>
import {generateHTML} from "@tiptap/html";

export default {
  name: 'tiptap.vue',
  computed: {
    output() {
      const doc = {
        'type': 'document',
        'content': [{
          'type': 'paragraph',
          'attrs': {
            'align': 'left'
          },
          'content': [{
            'type': 'text',
            'text': 'My sample text'
          }]
        }]
      }

      return generateHTML(doc, [
        Document,
        Text,
      ])
    },
  },
}
</script>

<style scoped>

</style>
```
So I am using the utility package? I don't see it

**Comment by hanspagel** [comment]
You pass `Document` but don’t import it. That’s why ut’s undefined.

Also, for the JSON included in your example you’ll need `Document`, `Paragraph` and `Text`, as shown in the first code block in your comment.

ProseMirror/tiptap is very strict with the so called schema. It only has support for the exact set of passed extensions and nothing more. So make sure to add `Bold` and everything else you might need too.

**Comment by stetim94** [comment]
That is just really stupid from my side. But now I am still not there, get a different error from prosemirror:
```
 ERROR  Unknown node type: document                                                                                                                                                                                                                                                                                                                              07:33:59

  at Schema.nodeType (node_modules/prosemirror-model/dist/index.js:2409:23)
  at Function.fromJSON (node_modules/prosemirror-model/dist/index.js:1379:17)
  at generateHTML (node_modules/@tiptap/html/dist/tiptap-html.cjs.js:21:47)
  at a.output (client/pages/tiptap.vue:32:0)
  at a.output (node_modules/vue/dist/vue.runtime.common.prod.js:6:29698)
  at a.render (client/pages/tiptap.vue)
  at a.t._render (node_modules/vue/dist/vue.runtime.common.prod.js:6:35273)
  at node_modules/vue-server-renderer/build.prod.js:1:70637
  at Yi (node_modules/vue-server-renderer/build.prod.js:1:67201)
  at io (node_modules/vue-server-renderer/build.prod.js:1:70613)
```
code:
```
<template>
  <div>
    {{ output }}
  </div>
</template>

<script>
import {generateHTML} from "@tiptap/html";
import Document from '@tiptap/extension-document'
import Paragraph from '@tiptap/extension-paragraph'
import Text from '@tiptap/extension-text'
import Bold from '@tiptap/extension-bold'

export default {
  name: 'tiptap.vue',
  computed: {
    output() {
      const doc = {
        'type': 'document',
        'content': [{
          'type': 'paragraph',
          'attrs': {
            'align': 'left'
          },
          'content': [{
            'type': 'text',
            'text': 'My sample text'
          }]
        }]
      }

      return generateHTML(doc, [
        Document,
        Text,
        Paragraph,
        Bold,
      ])
    },
  },
}
</script>

<style scoped>

</style>
```

**Comment by hanspagel** [comment]
I know it’s a little bit confusing, but the internal type of `Document` is actually `doc`. Try changing that name in the passed JSON.

We wanted to go with `document` but changed it back to the ProseMirror default `doc` to avoid trouble with 3rd party packages.

Anyway, that shouldn’t happen if you use the real output of the editor.

**Comment by stetim94** [comment]
That works, thank you so much. I feel so stupid now, bit overwhelmed by all the information I suppose.

**Comment by hanspagel** [comment]
No worries, it’s a lot to learn. Happy to help!
