### ISSUE TITLE
TypeError: Cannot read property 'addExtensions' of undefined

### ISSUE THREAD

**Issue by hardiksondagar** [ueberdosis/tiptap#1545]
**Description**
Error while creating Ydoc using TipTapTransformer

**Steps to reproduce the bug**
Follow steps mentioned in documentation to import document https://www.hocuspocus.dev/guide/documents/#importing-documents

**CodeSandbox**
I created a CodeSandbox to help you debug the issue:

* Node: https://codesandbox.io/s/jolly-rgb-c6xbl?file=/src/index.js

**Expected behavior**
It should have returned Ydoc object

**Additional context**
My use case it to load document on `onCreateDocument` event in hocuspocus server. It fetches HTML data from an API and converts it into Ydoc.

**Comment by hardiksondagar** [comment]
```
{ type: 'doc', content: [ { type: 'paragraph', content: [Array] } ] }
/sandbox/node_modules/@tiptap/core/dist/tiptap-core.cjs.js:427
    if (extension.config[field] === undefined && extension.parent) {
                        ^

TypeError: Cannot read property 'addExtensions' of undefined
    at getExtensionField (/sandbox/node_modules/@tiptap/core/dist/tiptap-core.cjs.js:427:25)
    at /sandbox/node_modules/@tiptap/core/dist/tiptap-core.cjs.js:816:35
    at Array.map (<anonymous>)
    at Function.flatten (/sandbox/node_modules/@tiptap/core/dist/tiptap-core.cjs.js:811:14)
    at Function.resolve (/sandbox/node_modules/@tiptap/core/dist/tiptap-core.cjs.js:807:55)
    at Object.getSchema (/sandbox/node_modules/@tiptap/core/dist/tiptap-core.cjs.js:3251:49)
    at Tiptap.toYdoc (/sandbox/node_modules/@hocuspocus/transformer/dist/hocuspocus-transformer.cjs:9915:72)
    at Object.<anonymous> (/sandbox/src/index.js:15:26)

**Comment by devgeni** [comment]
I'm having the same issue. Trying to transform html string to y-doc.

This is from the **onCreateDocument** hook:
`return TiptapTransformer.toYdoc("<h1>Test</h1>", "default", [StarterKit]);`

Doesn't work with json format either...

**Comment by hanspagel** [comment]
Please open an issue in the hocuspocus repository.

**Comment by devgeni** [comment]
Sorry, but this actually doesn't relate to hocuspocus. The problem is with extensions.

Consider this code:
```
import Document from "@tiptap/extension-document";
import Paragraph from "@tiptap/extension-paragraph";
import Text from "@tiptap/extension-text";

import { generateJSON } from "@tiptap/html";

const html = "<p>Hello World</p>";
const json = generateJSON(html, [Document, Paragraph, Text]);

console.log(json);
```

It throws the same error:
`TypeError: Cannot read property 'addExtensions' of undefined
    at getExtensionField...`


But the code below works as expected:
```
import { Node } from '@tiptap/core'
import { generateJSON } from "@tiptap/html";

const Document = Node.create({
  name: 'doc',
  topNode: true,
  content: 'block+',
});

const Paragraph = Node.create({
  name: 'paragraph',
  group: 'block',
  content: 'inline*',
  parseHTML() {
    return [
      { tag: 'p' },
    ]
  },
  renderHTML({ HTMLAttributes }) {
    return ['p', HTMLAttributes, 0]
  },
});

const Text = Node.create({
  name: 'text',
  group: 'inline',
});

const html = "<p>Hello World</p>";
const json = generateJSON(html, [Document, Paragraph, Text]);

console.log(json);
```

It outputs:
`{ type: 'doc', content: [ { type: 'paragraph', content: [Array] } ] }`

**Comment by hardiksondagar** [comment]
Looks like extensions of hocuspocus & tiptap have different structure and how `html-to-prosemirror` is using it.

I've solved it by importing `Document.Document` instead of `Document`
```
// const Document = require("@tiptap/extension-document");
const Document = require("@tiptap/extension-document").Document;
// const Text = require("@tiptap/extension-text");
const Text = require("@tiptap/extension-text").Text;
// const Paragraph = require("@tiptap/extension-paragraph");
const Paragraph = require("@tiptap/extension-paragraph").Paragraph;
const { TiptapTransformer } = require("@hocuspocus/transformer");
const HTMLtoProsemirror = require("html-to-prosemirror").Renderer;

const renderer = new HTMLtoProsemirror();

const htmlContent = "<p>Heading</p>";

let content = renderer.render(htmlContent);
console.log(content);

const transformer = TiptapTransformer.extensions([Document, Paragraph, Text]);
const ydoc = transformer.toYdoc(content, "default");
console.log(ydoc);

```


Side note: I couldn’t easily find tiptap's html generator initially, hence used `html-to-prosemirror` convertor.  May be more example can be added with regards to html. Because in realworld application would want actual data to be stored in html or text only instead of complex JSON structure that can't be read easily.

**Comment by philippkuehn** [comment]
when using node.js you have to use names imports.

so this:

```js
import { Document } from "@tiptap/extension-document";
import { Paragraph } from "@tiptap/extension-paragraph";
import { Text } from "@tiptap/extension-text";
```

instead of this:
```js
import Document from "@tiptap/extension-document";
import Paragraph from "@tiptap/extension-paragraph";
import Text from "@tiptap/extension-text";
```
