### ISSUE TITLE
Unexpected token 'export',  nuxt 3

### ISSUE THREAD

**Issue by claranceliberi** [ueberdosis/tiptap#2127]
### What’s the bug you are facing?

I am installing tiptap with vite and nuxt 3 but i am getting a bug 

```
       13:00:45
(node:22183) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
Unexpected token 'export'
  at wrapSafe (internal/modules/cjs/loader.js:1001:16)  
  at Module._compile (internal/modules/cjs/loader.js:1049:27)  
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)  
  at Module.load (internal/modules/cjs/loader.js:950:32)  
  at Function.Module._load (internal/modules/cjs/loader.js:790:12)  
  at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)  
  at ModuleJob.run (internal/modules/esm/module_job.js:183:25)  
  at async Loader.import (internal/modules/esm/loader.js:178:24)  
  at async __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:28249:3)
Unexpected token 'export'
  at wrapSafe (internal/modules/cjs/loader.js:1001:16)  
  at Module._compile (internal/modules/cjs/loader.js:1049:27)  
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)  
  at Module.load (internal/modules/cjs/loader.js:950:32)  
  at Function.Module._load (internal/modules/cjs/loader.js:790:12)  
  at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)  
  at ModuleJob.run (internal/modules/esm/module_job.js:183:25)  
  at async Loader.import (internal/modules/esm/loader.js:178:24)  
  at async __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:28249:3)
Unexpected token 'export'
  at wrapSafe (internal/modules/cjs/loader.js:1001:16)  
  at Module._compile (internal/modules/cjs/loader.js:1049:27)  
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)  
  at Module.load (internal/modules/cjs/loader.js:950:32)  
  at Function.Module._load (internal/modules/cjs/loader.js:790:12)  
  at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)  
  at ModuleJob.run (internal/modules/esm/module_job.js:183:25)  
  at async Loader.import (internal/modules/esm/loader.js:178:24)  
  at async __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:28249:3)
Unexpected token 'export'
  at wrapSafe (internal/modules/cjs/loader.js:1001:16)  
  at Module._compile (internal/modules/cjs/loader.js:1049:27)  
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)  
  at Module.load (internal/modules/cjs/loader.js:950:32)  
  at Function.Module._load (internal/modules/cjs/loader.js:790:12)  
  at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)  
  at ModuleJob.run (internal/modules/esm/module_job.js:183:25)  
  at async Loader.import (internal/modules/esm/loader.js:178:24)  
  at async __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:28249:3)
```

![image](https://user-images.githubusercontent.com/60586899/140050995-8f498193-af64-4f67-b629-5bc2b7524bed.png)

### How can we reproduce the bug on our side?

-  start nuxt 3 app 
-  add tiptap ` yarn add @tiptap/vue-3@latest @tiptap/starter-kit@latest` 
-  `yarn dev` 

### Can you provide a CodeSandbox?

https://stackblitz.com/github/claranceliberi/nuxt-tiptap

### What did you expect to happen?

I expected the tiptap to work fine without any error as it works in vue 3

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by AxelBriche** [comment]
Same probleme on my new project.

**Comment by hanspagel** [comment]
Nuxt 3 is pretty new and in beta, too, I don’t see Tiptap in the stack trace and it’s not that those issues appear with Next.js, Gatsby, Vite, SvelteKit or other frameworks. 

I’m afraid this could be more a Nuxt issue than a Tiptap issue. Would you mind to report it over there?
