### ISSUE TITLE
Error "window is not defined" in generateHTML

### ISSUE THREAD

**Issue by jclab-joseph** [ueberdosis/tiptap#2542]
### What’s the bug you are facing?

```
 ERROR  window is not defined

  at doc (node_modules\prosemirror-model\dist\index.js:3483:30)
  at DOMSerializer.serializeFragment (node_modules\prosemirror-model\dist\index.js:3323:27)
  at getHTMLFromFragment (node_modules\@tiptap\core\dist\tiptap-core.cjs.js:2240:10)
  at Object.generateHTML (node_modules\@tiptap\core\dist\tiptap-core.cjs.js:4242:12)
  at VueComponent.get functionName(page.js:104:71)
```

### How can we reproduce the bug on our side?

```
tiptap.generateHTML({
// tiptap json
}, [
 StarterKit
]);
```

### Can you provide a CodeSandbox?

https://codesandbox.io/s/node-tiptap-test-b399km?file=/src/index.js

### What did you expect to happen?

just it to work!

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
You have to use `@tiptap/html` for using `generateHTML` server-side. See: https://tiptap.dev/api/utilities/html
