### ISSUE TITLE
Vite `build` command fails

### ISSUE THREAD

**Issue by rich-choy** [ueberdosis/tiptap#2897]
### What’s the bug you are facing?

I have a Vite project that employs the TipTap editor (fantastic work, btw!). I am using the `@tiptap/starter-kit` package. I don't know if the root cause is Vite or this package, but I would appreciate eyes on it.

When I try to build my project using the `vite build` command, the build fails with this error:

```
[vite:resolve] Failed to resolve entry for package "@tiptap/starter-kit". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "@tiptap/starter-kit". The package may have incorrect main/module/exports specified in its package.json.
error during build:
Error: Failed to resolve entry for package "@tiptap/starter-kit". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "@tiptap/starter-kit". The package may have incorrect main/module/exports specified in its package.json.
    at packageEntryFailure (/Users/rchoy/var/bug/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:40945:11)
    at resolvePackageEntry (/Users/rchoy/var/bug/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:40941:9)
    at tryNodeResolve (/Users/rchoy/var/bug/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:40748:20)
    at Object.resolveId (/Users/rchoy/var/bug/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:40556:28)
    at /Users/rchoy/var/bug/node_modules/rollup/dist/shared/rollup.js:22868:37
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
```

### Which browser was this experienced in? Are any special extensions installed?

I encounter this problem at build time; not in a browser.

### How can we reproduce the bug on our side?

Here is a short video demonstrating that the project builds before adding a `@tiptap/starter-kit` import.

> https://www.loom.com/share/ee10b2db7a7847fa98401a6acf4a434b

## Steps

1. Scaffold a new Vite project as prescribed [here](https://vitejs.dev/guide/#scaffolding-your-first-vite-project).
2. Enter the newly created project root directory and install dependencies using the package manager of choice.
3. Add the `@tiptap/starter-kit` NPM dependency.
4. Add the following line to `src/App.tsx`:

    ```
    import '@tiptap/starter-kit';
    ```

5. Attempt to build the project by running the `build` npm script.

### Can you provide a CodeSandbox?

This problem only occurs during a Vite build. As such, it is not reproducible on CodeSandbox.

### What did you expect to happen?

I expect the Vite build to succeed without the error I described above.

### Anything to add? (optional)

Here is a short video demonstrating that the project builds before adding a `@tiptap/starter-kit` import.

> https://www.loom.com/share/ee10b2db7a7847fa98401a6acf4a434b

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by Cluster2a** [comment]
Same here with SvelteKit (1.0.0-next.350) and tiptap/starter-kit (2.0.0-beta.188).

**Comment by OliverGrimsley** [comment]
Same issue in Mix compile, and neither starter-kit nor vue-3 can be located.  Once I reverted back to old versions, my app compiled.  With the non working versions I get:

`ERROR in [wysiwygComponent.vue]?vue&type=script&setup=true&lang=js (./node_modules/babel-loader/lib/index.js??clonedRuleSet-5.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./resources/assets/js/components/formcomponents/wysiwygComponent.vue?vue&type=script&setup=true&lang=js) 1:0-54
Module not found: Error: Can't resolve '@tiptap/vue-3' in '/Users/michaeloliver/valetsites/starfile/resources/assets/js/components/formcomponents'`

`ERROR in [wysiwygComponent.vue]?vue&type=script&setup=true&lang=js (./node_modules/babel-loader/lib/index.js??clonedRuleSet-5.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./resources/assets/js/components/formcomponents/wysiwygComponent.vue?vue&type=script&setup=true&lang=js) 2:0-45
Module not found: Error: Can't resolve '@tiptap/starter-kit' in '/Users/michaeloliver/valetsites/starfile/resources/assets/js/components/formcomponents'`

I also was unable to uninstall these versions and install the old working ones, I had to get a copy from another machine.  

The correctly working versions:

```
"@tiptap/extension-link": "^2.0.0-beta.38",
"@tiptap/starter-kit": "^2.0.0-beta.185",
"@tiptap/vue-3": "^2.0.0-beta.91",
```

The versions that fail:
```
"@tiptap/extension-link": "^2.0.0-beta.41",
"@tiptap/starter-kit": "^2.0.0-beta.188",
"@tiptap/vue-3": "^2.0.0-beta.94",
```

**Comment by bdbch** [comment]
Hey! This sounds similar to the other issues we had with the faulty versions over this weekend. This should be resolved with our latest packages. Please update and try again! Thanks.

**Comment by Cluster2a** [comment]
@bdbch, thanks - works like charm with the new version :)
