### ISSUE TITLE
Input rules cause issues when `renderText` produces text that is matched by the input rule

### ISSUE THREAD

**Issue by arrocke** [ueberdosis/tiptap#2946]
### What’s the bug you are facing?

When `renderText` in a custom node produces text that is matched by a input rule, a position out of range error is triggered.

Our use case is to have dynamic nodes whose content is determined by an object of values at runtime. The node has a property name that it uses to pull off the value from that object. It's important for us that the text representation and the input rules are exactly the same.

### Which browser was this experienced in? Are any special extensions installed?

chrome, no relevant extensions

### How can we reproduce the bug on our side?

1. Create a node with a `renderText` that outputs some text (ie 'custom-node')
2. Add a node input rule that replaces the text with the node (ie `/custom-node/`)
3. In the editor, type the text that matches rule, that should work
4. Type it again, that should fail with the error

### Can you provide a CodeSandbox?

This is primitive and non-sensical, but demonstrates the behavior: https://codesandbox.io/s/tender-hill-l74pkp

### What did you expect to happen?

I would expect that node input rules should only process text nodes and not other custom nodes. Or at least be able to filter them out when matching.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by arrocke** [comment]
FWIW: this was working in @tiptap/core@2.0.0-beta.179, but it is broken in 2.0.0-beta.181

**Comment by svenadlung** [comment]
@arrocke Thanks for your report. There are some known issues with the input rules. If you have a change, could you give https://github.com/ueberdosis/tiptap/pull/2941 a try and see if this is affect your case?

**Comment by arrocke** [comment]
I don't think it will. Since my custom node has `renderText` defined, `toText` will execute before `$from.nodeBefore?.text` does

**Comment by arrocke** [comment]
Wondering if there is timeline for a fix on this? It's preventing us from upgrading to get fixes for other issues.

**Comment by ai-vta-alex** [comment]
Also having this issue.
Is there any workaround?

**Comment by drummerjolev** [comment]
Still having this issue as well

**Comment by kachkaev** [comment]
A bit surprised to see this unresolved. We want to have a simple inline `{{ pageNumber }}` block, but it seems to be impossible to implement. If `addInputRules` and `renderText` match the same pattern, `range` starts shifting left with each new character after `{{ pageNumber }}` until this like fails:

```ts
tr.replaceWith(range.from, range.to, this.type.create())
// ↑ Uncaught RangeError: Position -13 out of range
//    at ResolvedPos.resolve (index.js:1045:19)
//    at ResolvedPos.resolveCached (index.js:1077:56)
//    at Node.resolve (index.js:1376:39)
//    at replaceStep (index.js:1331:21)
//    at Transaction.replace (index.js:1958:20)
//    at Transaction.replaceWith (index.js:1968:21)
//    at InputRule.handler (page-number.ts:40:14)
```

Please help 🙏  We are tiptap pro users.

**Comment by bdbch** [comment]
Closing this for now - please ping me if this bug is still relevant on the latest stable version of Tiptap.
