### ISSUE TITLE
[Question] How to fix "Duplicate use of selection JSON ID cell" error?

### ISSUE THREAD

**Issue by matticustard** [ueberdosis/tiptap#316]
**Describe the bug**
As soon as I attempt to load the tiptap-extensions module using the example in the "Avaiable Extensions" section of the README, I receive the error: "Uncaught RangeError: Duplicate use of selection JSON ID cell."  This is in reference to a line of code: "prosemirrorState.Selection.jsonID("cell", CellSelection);"

I'm hoping there's something simple I'm overlooking, because I can't seem to find anyone else with this issue.

**Steps to Reproduce**
I have installed the tiptap and tiptap-extensions modules.  
I also installed the prosemirror-tables module based on NPM's insistence.

*The main tiptap module works fine when I create a simple editor-content component, as in the README.*

However, as soon as I attempt to load the tiptap-extensions module, I receive the error: "Uncaught RangeError: Duplicate use of selection JSON ID cell."  This is in reference to a line of code somewhere that reads: "prosemirrorState.Selection.jsonID("cell", CellSelection);"

**What have I done to try to fix this issue?**
 - I uninstalled and reinstalled the modules.
 - I have updated all other node modules.
 - I have tried removing and recreating the node_modules folder.
 - I have tried making the editor the only defined Vue component (commented out all others temporarily).
 - I have looked online for hours for a solution, whether with tiptap or prosemirror, and have been unsuccessful.

**Expected behavior**
For the editor to be able to load with extensions and menu.

**Environment (local)**
 - Windows 10
 - Chrome
 - Version 74.0.3729.131
 - Desktop

**Environment (remote)**
 - CentOS 6.10
 - Laravel 5.8
 - Webpack (via Laravel Mix)

**Comment by Alecyrus** [comment]
I met this error before，and fixed it by deleting node_modules and reinstalling the dependences.

**Comment by philippkuehn** [comment]
this is a version problem. why do you installed prosemirror-tables?

**Comment by matticustard** [comment]
> why do you installed prosemirror-tables?

Because I received this message upon installing tiptap:

npm WARN prosemirror-utils@0.8.1 requires a peer of prosemirror-tables@^0.7.9 but none is installed. You must install peer dependencies yourself.

And if I don't install it, I get this message from webpack:

ERROR in ./node_modules/prosemirror-utils/dist/index.js
Module not found: Error: Can't resolve 'prosemirror-tables' in '/home/...

**Comment by philippkuehn** [comment]
Hmm this is strange, because `prosemirror-tables` is already a dependency of `tiptap-extensions`.

**Comment by matticustard** [comment]
Just tried installing tiptap-extensions without prosemirror-tables installed to see if it would load the dependencies as you mention it should, but it gives the same error.

```
npm install tiptap-extensions
npm WARN prosemirror-utils@0.8.1 requires a peer of prosemirror-tables@^0.7.9 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ tiptap-extensions@1.19.4
added 9 packages from 270 contributors and audited 29151 packages in 12.765s
```

**Comment by matticustard** [comment]
So despite the error, it does seem to be working now.  I guess I should have just ignored the warning in the first place. Thanks for your help!

**Comment by JeffersonOndzeMangha** [comment]
I am facing this issue, none of the above comments fixed the issue, is there a more concrete response?

**Comment by mdtomo** [comment]
I had the same issue. Delete your node_modules directory, package.json.lock file and remove any references to `prosemirror-tables` from package.json. Then npm install.

**Comment by lpellis** [comment]
I also ran into this issue, what fixed it for me was installing with yarn instead of npm ¯\_(ツ)_/¯

**Comment by Ekkstein** [comment]
I just ran into the same issue and well, none of the above helped.

**Comment by andreasvirkus** [comment]
The same error is also on the official Codesandbox that is linked to when creating a new issue

https://codesandbox.io/s/qxv5m9y6oq

**Comment by gavinhewitt** [comment]
Having the same issue. I can't find anywhere where there's a call for a different version.

As a quick (but obviously unsustainable) fix I edit the file generated by webpack and remove the duplicate code.

**Comment by vssoft** [comment]
### Fixed error "Duplicate use of selection JSON ID cell":
In my vuejs project I had installed:
**npm install --save tiptap@1.27.1** 
(with WARN prosemirror-utils@0.9.6 requires a peer of prosemirror-tables@^0.9.1 but none is installed)
**npm install --save tiptap-extensions@1.29.1**
(with the same WARN)
(**Ignored both WARNs**)
When routing to page containing Tiptap, I got error "Duplicate use of selection JSON ID cell"
**To fix it:**
Went to .../myproject/node_modules/tiptap-extensions/ and **renamed subfolder** '/node-modules' **to** '/node-modules--'
Recompiled the project and **got no error** this time.
**Explained:** 
In .../myproject/node_modules/ contains folder '/prosemirror-tables' (version 1.1.1)
In .../myproject/node_modules/tiptap-extensions/node-modules/ contains folder '/prosemirror-tables' (version 1.0.0)
Loading duplicated modules with different versions raises the error.

**Comment by hanspagel** [comment]
This shouldn’t be an issue anymore with the recent release. 🙃

Happy to reopen, when someone encounters this issue again.

**Comment by peterkruty** [comment]
I just tried to upgrade and have the same problem. 

```
vue-router.esm.js?85f8:2128 RangeError: Duplicate use of selection JSON ID cell
    at Function.jsonID (index.es.js?ed9c:188)
    at eval (index.es.js?d5b1:708)
    at Module../node_modules/tiptap-extensions/node_modules/prosemirror-tables/dist/index.es.js (vendor.js:15211)
    at __webpack_require__ (app.js:854)
    at fn (app.js:151)
    at eval (extensions.esm.js?6301:1)
    at Module../node_modules/tiptap-extensions/dist/extensions.esm.js (vendor.js:15199)
    at __webpack_require__ (app.js:854)
    at fn (app.js:151)
    at eval (index.js?!./node_modules/@quasar/app/lib/webpack/loader.auto-import-client.js?kebab!./node_modules/vue-loader/lib/index.js?!./src/pages/auth/EvidenceBacklog-copy.vue?vue&type=script&lang=js&:7)
```

But the fix from @vssoft  worked just fine.

**Comment by DanieleSpera** [comment]
Same here

On installation:
npm WARN prosemirror-utils@0.9.6 requires a peer of prosemirror-tables@^0.9.1 but none is installed. You must install peer dependencies yourself.

On Extensions installation:
Uncaught RangeError: Duplicate use of selection JSON ID cell
    at Function.jsonID (index.es.js?5313:188)
    at eval (index.es.js?41dd:582)
    at Module../node_modules/tiptap-extensions/node_modules/prosemirror-tables/dist/index.es.js (chunk-vendors.js:10616)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
    at eval (extensions.esm.js?f23d:1)
    at Module../node_modules/tiptap-extensions/dist/extensions.esm.js (chunk-vendors.js:10592)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)

**Comment by peterkruty** [comment]
> I just tried to upgrade and have the same problem.
> 
> ```
> vue-router.esm.js?85f8:2128 RangeError: Duplicate use of selection JSON ID cell
>     at Function.jsonID (index.es.js?ed9c:188)
>     at eval (index.es.js?d5b1:708)
>     at Module../node_modules/tiptap-extensions/node_modules/prosemirror-tables/dist/index.es.js (vendor.js:15211)
>     at __webpack_require__ (app.js:854)
>     at fn (app.js:151)
>     at eval (extensions.esm.js?6301:1)
>     at Module../node_modules/tiptap-extensions/dist/extensions.esm.js (vendor.js:15199)
>     at __webpack_require__ (app.js:854)
>     at fn (app.js:151)
>     at eval (index.js?!./node_modules/@quasar/app/lib/webpack/loader.auto-import-client.js?kebab!./node_modules/vue-loader/lib/index.js?!./src/pages/auth/EvidenceBacklog-copy.vue?vue&type=script&lang=js&:7)
> ```
> 
> But the fix from @vssoft worked just fine.

This is bizzare. I just installed lodash into project and as I did that, I'm getting same error.

```
vue-router.esm.js?85f8:2128 RangeError: Duplicate use of selection JSON ID cell
    at Function.jsonID (index.es.js?ed9c:188)
    at eval (index.es.js?d5b1:708)
    at Module../node_modules/tiptap-extensions/node_modules/prosemirror-tables/dist/index.es.js (vendor.js:15463)
    at __webpack_require__ (app.js:854)
    at fn (app.js:151)
    at eval (extensions.esm.js?6301:1)
    at Module../node_modules/tiptap-extensions/dist/extensions.esm.js (vendor.js:15451)
    at __webpack_require__ (app.js:854)
    at fn (app.js:151)
    at eval (index.js?!./node_modules/@quasar/app/lib/webpack/loader.auto-import-client.js?kebab!./node_modules/vue-loader/lib/index.js?!./src/components/InsightVisualizations/EvidenceEditor.vue?vue&type=script&lang=js&:25)
```

**Comment by doquanghieu1769** [comment]
### 

> [`_****_`](url)

- [ ]

**Comment by TroubleZjb** [comment]
try 
```
npm i -S prosemirror-utils@^1.0.0-0
```
npm installs prosemirror-utils at verstion 0.9.6 by default, witch requires a peer of prosemirror-tables@^0.9.x. 
It cause error because tiptap requires prosemirror-tables@^1.0.0.

**Comment by gethari** [comment]
I am facing this problem. Please help. Prosemirror & tiptap packages used

```json
    "prosemirror-state": "^1.4.1",
    "prosemirror-tables": "^1.2.5",
    "@tiptap/core": "^2.0.0-beta.180",
    "@tiptap/extension-blockquote": "^2.0.0-beta.29",
    "@tiptap/extension-bold": "^2.0.0-beta.28",
    "@tiptap/extension-bubble-menu": "^2.0.0-beta.60",
    "@tiptap/extension-bullet-list": "^2.0.0-beta.29",
    "@tiptap/extension-character-count": "^2.0.0-beta.30",
    "@tiptap/extension-code": "^2.0.0-beta.28",
    "@tiptap/extension-code-block": "^2.0.0-beta.41",
    "@tiptap/extension-code-block-lowlight": "^2.0.0-beta.72",
    "@tiptap/extension-collaboration": "^2.0.0-beta.37",
    "@tiptap/extension-collaboration-cursor": "^2.0.0-beta.37",
    "@tiptap/extension-color": "^2.0.0-beta.12",
    "@tiptap/extension-document": "^2.0.0-beta.17",
    "@tiptap/extension-dropcursor": "^2.0.0-beta.28",
    "@tiptap/extension-floating-menu": "^2.0.0-beta.55",
    "@tiptap/extension-focus": "^2.0.0-beta.44",
    "@tiptap/extension-font-family": "^2.0.0-beta.24",
    "@tiptap/extension-gapcursor": "^2.0.0-beta.38",
    "@tiptap/extension-hard-break": "^2.0.0-beta.33",
    "@tiptap/extension-heading": "^2.0.0-beta.29",
    "@tiptap/extension-highlight": "^2.0.0-beta.35",
    "@tiptap/extension-history": "^2.0.0-beta.25",
    "@tiptap/extension-horizontal-rule": "^2.0.0-beta.35",
    "@tiptap/extension-image": "^2.0.0-beta.30",
    "@tiptap/extension-italic": "^2.0.0-beta.28",
    "@tiptap/extension-link": "^2.0.0-beta.42",
    "@tiptap/extension-list-item": "^2.0.0-beta.23",
    "@tiptap/extension-mention": "^2.0.0-beta.101",
    "@tiptap/extension-ordered-list": "^2.0.0-beta.30",
    "@tiptap/extension-paragraph": "^2.0.0-beta.26",
    "@tiptap/extension-placeholder": "^2.0.0-beta.52",
    "@tiptap/extension-strike": "^2.0.0-beta.29",
    "@tiptap/extension-subscript": "^2.0.0-beta.13",
    "@tiptap/extension-superscript": "^2.0.0-beta.13",
    "@tiptap/extension-table": "^2.0.0-beta.53",
    "@tiptap/extension-table-cell": "^2.0.0-beta.23",
    "@tiptap/extension-table-header": "^2.0.0-beta.25",
    "@tiptap/extension-table-row": "^2.0.0-beta.22",
    "@tiptap/extension-task-item": "^2.0.0-beta.36",
    "@tiptap/extension-task-list": "^2.0.0-beta.29",
    "@tiptap/extension-text": "^2.0.0-beta.17",
    "@tiptap/extension-text-align": "^2.0.0-beta.31",
    "@tiptap/extension-text-style": "^2.0.0-beta.26",
    "@tiptap/extension-typography": "^2.0.0-beta.22",
    "@tiptap/extension-underline": "^2.0.0-beta.25",
    "@tiptap/extension-youtube": "^2.0.0-beta.5",
    "@tiptap/starter-kit": "^2.0.0-beta.189",
```

![image](https://user-images.githubusercontent.com/20477956/183024946-acb78e6a-23ef-470a-a450-376faf4ccfb6.png)

**Comment by intuitiveminds** [comment]
For anyone still facing this issue - this has helped me without needing to modify any files in node_modules. I added this snippet to my package.json:

```
"overrides": {
    "prosemirror-tables": "1.2.5"
}
```

Then I ran `npm install` and the error was gone, because as @TroubleZjb already pointed out the problem is that two conflicting versions of prosemirror-tables were installed.

**Comment by jonalxh** [comment]
@intuitiveminds Solution is not working for me, I have the following versions:
```
    "@tiptap/extension-image": "^2.0.0-beta.30",
    "@tiptap/extension-link": "^2.0.0-beta.43",
    "@tiptap/extension-table": "^2.0.0-beta.199",
    "@tiptap/extension-table-cell": "^2.0.0-beta.199",
    "@tiptap/extension-table-header": "^2.0.0-beta.199",
    "@tiptap/extension-table-row": "^2.0.0-beta.199",
    "@tiptap/starter-kit": "^2.0.0-beta.192",
    "@tiptap/vue-2": "^2.0.0-beta.85",
```

**Comment by gary-dgc** [comment]
> ### Fixed error "Duplicate use of selection JSON ID cell":
> In my vuejs project I had installed: **npm install --save tiptap@1.27.1** (with WARN prosemirror-utils@0.9.6 requires a peer of prosemirror-tables@^0.9.1 but none is installed) **npm install --save tiptap-extensions@1.29.1** (with the same WARN) (**Ignored both WARNs**) When routing to page containing Tiptap, I got error "Duplicate use of selection JSON ID cell" **To fix it:** Went to .../myproject/node_modules/tiptap-extensions/ and **renamed subfolder** '/node-modules' **to** '/node-modules--' Recompiled the project and **got no error** this time. **Explained:** Folder .../myproject/node_modules/ contains subfolder '/prosemirror-tables' (version 1.1.1) Folder .../myproject/node_modules/tiptap-extensions/node-modules/ contains subfolder '/prosemirror-tables' (version 1.0.0) Loading duplicated modules with different versions raises the error.

I lock the package version fix the issue:
    "tiptap": "1.30.0",
    "tiptap-commands": "1.15.0",
    "tiptap-extensions": "1.33.0",
with these version, the prosemirror-tables and prosemirror-utils not wrapped with tiptap-commands and tiptap-extensions respectively, the root issue mentioned above is fixed.

**Comment by jonahallibone** [comment]
Just hit this error +1

**Comment by lisandrop05** [comment]
same problem here, none of the previous fixes solve the problem.

**Comment by Pckool** [comment]
+1 here! Getting this issue and none of the above worked

**Comment by jonahallibone** [comment]
Should this issue be reopened?

**Comment by krank56** [comment]
up up up

**Comment by jonahallibone** [comment]
For myself, I only use tiptap and frequently still get this error in development. Frequently on page navigation in Next.js

**Comment by christophermiles** [comment]
I suddenly started getting this error, even though I haven't updated or installed any other dependencies. After a hot reload in a Vite / Vue project following a code change completely unrelated to TipTap, I suddenly stared getting this error.

Tried @gary-dgc's suggestion and reinstalled all packages and still getting this issue. Absolutely bizarre.

**Comment by zoltanszogyenyi** [comment]
Same here, getting this error on our WYSIWYG component out of the nowhere:

https://flowbite.com/docs/plugins/wysiwyg/

Mostly for the tables example:

https://flowbite.com/docs/plugins/wysiwyg/#editing-tables

```
index.js:178 Uncaught RangeError: Duplicate use of selection JSON ID cell
    at l.jsonID (index.js:178:19)
    at index.js:741:11
```

We use `v2.6.6` and this code worked perfectly before, we didn't change our code, config or version.
