### ISSUE TITLE
Vite.js and  @tiptap/vue-3   2.0.0-beta.195

### ISSUE THREAD

**Issue by myalban** [ueberdosis/tiptap#3202]
### What’s the bug you are facing?

I got this issue when I try to load the editor  and use vite.js to build : 

index.js:2239 Uncaught (in promise) RangeError: Schema is missing its top node type ('doc')
    at NodeType.compile (index.js:2239:19)
    at new Schema (index.js:2365:31)
    at getSchemaByResolvedExtensions (getSchemaByResolvedExtensions.ts:143:10)
    at new ExtensionManager (ExtensionManager.ts:35:19)
    at Editor2.createExtensionManager (Editor.ts:244:29)
    at new Editor (Editor.ts:83:10)
    at new Editor2 (Editor.ts:50:5)
    at useEditor.ts:10:20
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)

### Which browser was this experienced in? Are any special extensions installed?

google chrome browser

### How can we reproduce the bug on our side?

Try to compile with vite.js

### Can you provide a CodeSandbox?

Here is my code 

<template>
  <editor-content :editor="editor" />
</template>

<script setup lang="ts">
import {useEditor, EditorContent} from "@tiptap/vue-3";

const editor = useEditor({
  content: "<p>I’m running Tiptap with Vue.js.</p>",
  extensions: [],
});
</script>

### What did you expect to happen?

I'm expecting to see the editor

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
@myalban you need to add extensions to your editor.

```bash
npm i @tiptap/starter-kit
```

and then

```js
import StarterKit from '@tiptap/vue-3'

const editor = useEditor({
    content: "I'm running Tiptap with Vue.js",
    extensions: [StarterKit]
})
```
