### ISSUE TITLE
Editor doesn’t call onBlur callback in testing environment

### ISSUE THREAD

**Issue by kolosovsky** [ueberdosis/tiptap#3441]
### What’s the bug you are facing?

While testing my React component with Jest I execute `editor.commands.blur()` but for some reason `onBlur` callback is not called. I also tried to trigger it calling `window.dispatchEvent(new FocusEvent())` without success.

### Which browser was this experienced in? Are any special extensions installed?

I experience it in testing environment (Jest)

### How can we reproduce the bug on our side?

Just try to execute `editor.commands.blur()`, in this case `onBlur` is not called.

### What did you expect to happen?

I expected `onBlur` to be called.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bartoszswitalski** [comment]
Similar problem here. When testing, I am only able to trigger `beforeCreate()` callback of `useEditor` hook.

**Comment by ojh** [comment]
I have a similar issue (although I'm using Vue.js). I am able to use Testing Library to successfully type into the editor, as per this test: 

```typescript
import { describe, it, expect } from "vitest";
import { getByText } from "@testing-library/dom";
import { flushPromises } from "@vue/test-utils";
import { render } from "@testing-library/vue";
import userEvent from "@testing-library/user-event";
import MyTiptapComponent from "@/components/MyTiptapComponent.vue";

describe("MyTiptapComponent", () => {
  it("updates content when typed into", async () => {
    const user = userEvent.setup();
    const { getByText } = render(MyTiptapComponent, {
      props: { content: "Test" },
    });
    await flushPromises();

    const textbox = getByText("Test").parentElement!;
    await user.type(textbox, "ing");

    expect(textbox.textContent).toBe("Testing");
  });
});
```

However, although the test is green, the console output is polluted by the following error messages:

```bash
stderr | src/components/__tests__/MyTiptapComponent.spec.ts > MyTiptapComponent events > updates content when typed into
Error: Uncaught [TypeError: (intermediate value)(intermediate value)(intermediate value).elementFromPoint is not a function]
    at reportException (/home/.../node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
    at innerInvokeEventListeners (/home/.../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:353:9)
    at invokeEventListeners (/home/.../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:286:3)
    at HTMLDivElementImpl._dispatch (/home/.../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:233:9)
    at HTMLDivElementImpl.dispatchEvent (/home/.../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:104:17)
    at HTMLDivElement.dispatchEvent (/home/.../node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:241:34)
    at file:///home/.../node_modules/@testing-library/user-event/dist/index.mjs:1732:33
    at Object.eventWrapper (/home/.../node_modules/@testing-library/dom/dist/config.js:27:23)
    at wrapEvent (file:///home/.../node_modules/@testing-library/user-event/dist/index.mjs:1706:23)
    at dispatchEvent (file:///home/.../node_modules/@testing-library/user-event/dist/index.mjs:1732:10)
    at dispatchUIEvent (file:///home/.../node_modules/@testing-library/user-event/dist/index.mjs:1741:10)
    at firePointerEvent (file:///home/.../node_modules/@testing-library/user-event/dist/index.mjs:2202:10)
    at fire (file:///home/.../node_modules/@testing-library/user-event/dist/index.mjs:2424:12)
    at down (file:///home/.../node_modules/@testing-library/user-event/dist/index.mjs:2406:37)
    at file:///home/.../node_modules/@testing-library/user-event/dist/index.mjs:2347:21
    at Generator.next (<anonymous>)
    at file:///home/.../node_modules/@testing-library/user-event/dist/index.mjs:43:61
    at new Promise (<anonymous>)
    at __async (file:///home/.../node_modules/@testing-library/user-event/dist/index.mjs:27:10)
    at pointerPress (file:///home/.../node_modules/@testing-library/user-event/dist/index.mjs:2338:10)
    at file:///home/.../node_modules/@testing-library/user-event/dist/index.mjs:2572:34
    at Generator.next (<anonymous>)
    at fulfilled (file:///home/.../node_modules/@testing-library/user-event/dist/index.mjs:30:24) TypeError: (intermediate value)(intermediate value)(intermediate value).elementFromPoint is not a function
    at _posAtCoords (/home/.../node_modules/prosemirror-view/dist/index.cjs:447:60)
    at EditorView.posAtCoords (/home/.../node_modules/prosemirror-view/dist/index.cjs:5576:14)
    at handlers.mousedown (/home/.../node_modules/prosemirror-view/dist/index.cjs:3455:18)
    at view.dom.addEventListener.view.input.eventHandlers.<computed> (/home/.../node_modules/prosemirror-view/dist/index.cjs:3195:130)
    at HTMLDivElement.callTheUserObjectsOperation (/home/.../node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
    at innerInvokeEventListeners (/home/.../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:350:25)
    at invokeEventListeners (/home/.../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:286:3)
    at HTMLDivElementImpl._dispatch (/home/.../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:233:9)
    at HTMLDivElementImpl.dispatchEvent (/home/.../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:104:17)
    at HTMLDivElement.dispatchEvent (/home/.../node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:241:34)
    at file:///home/.../node_modules/@testing-library/user-event/dist/index.mjs:1732:33
    at Object.eventWrapper (/home/.../node_modules/@testing-library/dom/dist/config.js:27:23)
    at wrapEvent (file:///home/.../node_modules/@testing-library/user-event/dist/index.mjs:1706:23)
    at dispatchEvent (file:///home/.../node_modules/@testing-library/user-event/dist/index.mjs:1732:10)
    at dispatchUIEvent (file:///home/.../node_modules/@testing-library/user-event/dist/index.mjs:1741:10)
    at firePointerEvent (file:///home/.../node_modules/@testing-library/user-event/dist/index.mjs:2202:10)
    at fire (file:///home/.../node_modules/@testing-library/user-event/dist/index.mjs:2424:12)
    at down (file:///home/.../node_modules/@testing-library/user-event/dist/index.mjs:2406:37)
    at file:///home/.../node_modules/@testing-library/user-event/dist/index.mjs:2347:21
    at Generator.next (<anonymous>)
    at file:///home/.../node_modules/@testing-library/user-event/dist/index.mjs:43:61
    at new Promise (<anonymous>)
    at __async (file:///home/.../node_modules/@testing-library/user-event/dist/index.mjs:27:10)
    at pointerPress (file:///home/.../node_modules/@testing-library/user-event/dist/index.mjs:2338:10)
    at file:///home/.../node_modules/@testing-library/user-event/dist/index.mjs:2572:34
    at Generator.next (<anonymous>)
    at fulfilled (file:///home/.../node_modules/@testing-library/user-event/dist/index.mjs:30:24)
Error: Uncaught [TypeError: target.getClientRects is not a function]
    at reportException (/home/.../node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
    at notifyMutationObservers (/home/.../node_modules/jsdom/lib/jsdom/living/helpers/mutation-observers.js:169:9)
    at /home/.../node_modules/jsdom/lib/jsdom/living/helpers/mutation-observers.js:133:5 TypeError: target.getClientRects is not a function
    at singleRect (/home/.../node_modules/prosemirror-view/dist/index.cjs:489:22)
    at _coordsAtPos (/home/.../node_modules/prosemirror-view/dist/index.cjs:554:33)
    at EditorView.coordsAtPos (/home/.../node_modules/prosemirror-view/dist/index.cjs:5582:14)
    at EditorView.updateStateInner (/home/.../node_modules/prosemirror-view/dist/index.cjs:5476:41)
    at EditorView.updateState (/home/.../node_modules/prosemirror-view/dist/index.cjs:5400:12)
    at Editor.dispatchTransaction (/home/.../node_modules/@tiptap/core/dist/tiptap-core.cjs.js:3221:19)
    at EditorView.dispatch (/home/.../node_modules/prosemirror-view/dist/index.cjs:5640:52)
    at readDOMChange (/home/.../node_modules/prosemirror-view/dist/index.cjs:5183:8)
    at DOMObserver.handleDOMChange (/home/.../node_modules/prosemirror-view/dist/index.cjs:5339:14)
    at DOMObserver.flush (/home/.../node_modules/prosemirror-view/dist/index.cjs:4856:14)
    at DOMObserver.observer (/home/.../node_modules/prosemirror-view/dist/index.cjs:4686:44)
    at MutationObserver.invokeTheCallbackFunction (/home/.../node_modules/jsdom/lib/jsdom/living/generated/MutationCallback.js:19:26)
    at notifyMutationObservers (/home/.../node_modules/jsdom/lib/jsdom/living/helpers/mutation-observers.js:160:22)
    at /home/.../node_modules/jsdom/lib/jsdom/living/helpers/mutation-observers.js:133:5

stderr | src/components/__tests__/MyTiptapComponent.spec.ts > MyTiptapComponent events > updates content when typed into
Error: Uncaught [RangeError: Applying a mismatched transaction]
    at reportException (/home/.../node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
    at notifyMutationObservers (/home/.../node_modules/jsdom/lib/jsdom/living/helpers/mutation-observers.js:169:9)
    at /home/.../node_modules/jsdom/lib/jsdom/living/helpers/mutation-observers.js:133:5 RangeError: Applying a mismatched transaction
    at EditorState.applyInner (/home/.../node_modules/prosemirror-state/dist/index.cjs:870:42)
    at EditorState.applyTransaction (/home/.../node_modules/prosemirror-state/dist/index.cjs:818:27)
    at EditorState.apply (/home/.../node_modules/prosemirror-state/dist/index.cjs:794:19)
    at Editor.dispatchTransaction (/home/.../node_modules/@tiptap/core/dist/tiptap-core.cjs.js:3219:34)
    at EditorView.dispatch (/home/.../node_modules/prosemirror-view/dist/index.cjs:5640:52)
    at readDOMChange (/home/.../node_modules/prosemirror-view/dist/index.cjs:5183:8)
    at DOMObserver.handleDOMChange (/home/.../node_modules/prosemirror-view/dist/index.cjs:5339:14)
    at DOMObserver.flush (/home/.../node_modules/prosemirror-view/dist/index.cjs:4856:14)
    at DOMObserver.observer (/home/.../node_modules/prosemirror-view/dist/index.cjs:4686:44)
    at MutationObserver.invokeTheCallbackFunction (/home/.../node_modules/jsdom/lib/jsdom/living/generated/MutationCallback.js:19:26)
    at notifyMutationObservers (/home/.../node_modules/jsdom/lib/jsdom/living/helpers/mutation-observers.js:160:22)
    at /home/.../node_modules/jsdom/lib/jsdom/living/helpers/mutation-observers.js:133:5

stderr | src/components/__tests__/MyTiptapComponent.spec.ts > MyTiptapComponent events > updates content when typed into
Error: Uncaught [RangeError: Applying a mismatched transaction]
    at reportException (/home/.../node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
    at notifyMutationObservers (/home/.../node_modules/jsdom/lib/jsdom/living/helpers/mutation-observers.js:169:9)
    at /home/.../node_modules/jsdom/lib/jsdom/living/helpers/mutation-observers.js:133:5 RangeError: Applying a mismatched transaction
    at EditorState.applyInner (/home/.../node_modules/prosemirror-state/dist/index.cjs:870:42)
    at EditorState.applyTransaction (/home/.../node_modules/prosemirror-state/dist/index.cjs:818:27)
    at EditorState.apply (/home/.../node_modules/prosemirror-state/dist/index.cjs:794:19)
    at Editor.dispatchTransaction (/home/.../node_modules/@tiptap/core/dist/tiptap-core.cjs.js:3219:34)
    at EditorView.dispatch (/home/.../node_modules/prosemirror-view/dist/index.cjs:5640:52)
    at readDOMChange (/home/.../node_modules/prosemirror-view/dist/index.cjs:5183:8)
    at DOMObserver.handleDOMChange (/home/.../node_modules/prosemirror-view/dist/index.cjs:5339:14)
    at DOMObserver.flush (/home/.../node_modules/prosemirror-view/dist/index.cjs:4856:14)
    at DOMObserver.observer (/home/.../node_modules/prosemirror-view/dist/index.cjs:4686:44)
    at MutationObserver.invokeTheCallbackFunction (/home/.../node_modules/jsdom/lib/jsdom/living/generated/MutationCallback.js:19:26)
    at notifyMutationObservers (/home/.../node_modules/jsdom/lib/jsdom/living/helpers/mutation-observers.js:160:22)
    at /home/.../node_modules/jsdom/lib/jsdom/living/helpers/mutation-observers.js:133:5

 ❯ src/components/__tests__/MyTiptapComponent.spec.ts (1) 312ms
   ❯ MyTiptapComponent events (1)
     ✓ updates content when typed into
```

Additionally, adding the following assertion to the test makes it fail unexpectedly, despite the `onUpdate` event listener being called successfully when testing in the browser:

```typescript
    expect(Object.keys(emitted())).toContain("update");
```

Upon inspection, the emitted events object looks like this by the end of my test:

```js
{
  create: [ [ [Object] ] ],
  pointerover: [ [ [Event] ] ],
  mouseover: [ [ [MouseEvent] ] ],
  pointermove: [ [ [Event] ] ],
  mousemove: [ [ [MouseEvent] ] ],
  pointerdown: [ [ [Event] ] ],
  mousedown: [ [ [MouseEvent] ] ],
  focusin: [ [ [FocusEvent] ] ],
  pointerup: [ [ [Event] ] ],
  mouseup: [ [ [MouseEvent] ] ],
  click: [ [ [MouseEvent] ] ],
  keydown: [ [ [KeyboardEvent] ], [ [KeyboardEvent] ], [ [KeyboardEvent] ] ],
  keypress: [ [ [KeyboardEvent] ], [ [KeyboardEvent] ], [ [KeyboardEvent] ] ],
  input: [ [ [InputEvent] ], [ [InputEvent] ], [ [InputEvent] ] ],
  keyup: [ [ [KeyboardEvent] ], [ [KeyboardEvent] ], [ [KeyboardEvent] ] ]
}
```

So my questions are:
1. Why don't I see an `update` event when inspecting Testing Library's `emitted()` object? :confused: 
2. What can I do about all the noise being produced in my test output? :nauseated_face:
