### ISSUE TITLE
Tiptap dependencies completely broken

### ISSUE THREAD

**Issue by bigboggy** [ueberdosis/tiptap#3690]
### What’s the bug you are facing?

Hey, 
we're using vite with vue and it's impossible to build or run the project on development anymore.
Our features depend on tiptap as well. How could it be that packages disappear into a black hole?

These are the error messages:
```
✘ [ERROR] Could not resolve "@tiptap/pm/state"

    node_modules/@tiptap/extension-focus/dist/index.js:3:34:
      3 │ import { Plugin, PluginKey } from "@tiptap/pm/state";
        ╵                                   ~~~~~~~~~~~~~~~~~~

  You can mark the path "@tiptap/pm/state" as external to exclude it from the bundle, which will
  remove this error.

✘ [ERROR] Could not resolve "@tiptap/pm/state"

    node_modules/@tiptap/extension-horizontal-rule/dist/index.js:3:30:
      3 │ import { TextSelection } from "@tiptap/pm/state";
        ╵                               ~~~~~~~~~~~~~~~~~~

  You can mark the path "@tiptap/pm/state" as external to exclude it from the bundle, which will
  remove this error.

✘ [ERROR] Could not resolve "@tiptap/pm/gapcursor"

    node_modules/@tiptap/extension-gapcursor/dist/index.js:7:26:
      7 │ import { gapCursor } from "@tiptap/pm/gapcursor";
        ╵                           ~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@tiptap/pm/gapcursor" as external to exclude it from the bundle, which will
  remove this error.

✘ [ERROR] Could not resolve "@tiptap/pm/state"

    node_modules/@tiptap/extension-mention/dist/index.js:3:26:
      3 │ import { PluginKey } from "@tiptap/pm/state";
        ╵                           ~~~~~~~~~~~~~~~~~~

  You can mark the path "@tiptap/pm/state" as external to exclude it from the bundle, which will
  remove this error.

✘ [ERROR] Could not resolve "@tiptap/pm/state"

    node_modules/@tiptap/extension-placeholder/dist/index.js:3:23:
      3 │ import { Plugin } from "@tiptap/pm/state";
        ╵                        ~~~~~~~~~~~~~~~~~~

  You can mark the path "@tiptap/pm/state" as external to exclude it from the bundle, which will
  remove this error.

✘ [ERROR] Could not resolve "@tiptap/pm/view"

    node_modules/@tiptap/extension-focus/dist/index.js:4:42:
      4 │ import { Decoration, DecorationSet } from "@tiptap/pm/view";
        ╵                                           ~~~~~~~~~~~~~~~~~

  You can mark the path "@tiptap/pm/view" as external to exclude it from the bundle, which will
  remove this error.

✘ [ERROR] Could not resolve "@tiptap/pm/state"

    node_modules/@tiptap/core/dist/index.js:152:7:
      152 │ } from "@tiptap/pm/state";
          ╵        ~~~~~~~~~~~~~~~~~~

  You can mark the path "@tiptap/pm/state" as external to exclude it from the bundle, which will
  remove this error.

✘ [ERROR] Could not resolve "@tiptap/pm/state"

    node_modules/@tiptap/extension-link/dist/index.js:12:34:
      12 │ import { Plugin, PluginKey } from "@tiptap/pm/state";
         ╵                                   ~~~~~~~~~~~~~~~~~~

  You can mark the path "@tiptap/pm/state" as external to exclude it from the bundle, which will
  remove this error.

✘ [ERROR] Could not resolve "@tiptap/pm/view"

    node_modules/@tiptap/extension-placeholder/dist/index.js:4:42:
      4 │ import { Decoration, DecorationSet } from "@tiptap/pm/view";
        ╵                                           ~~~~~~~~~~~~~~~~~

  You can mark the path "@tiptap/pm/view" as external to exclude it from the bundle, which will
  remove this error.

✘ [ERROR] Could not resolve "@tiptap/pm/view"

    node_modules/@tiptap/core/dist/index.js:153:27:
      153 │ import { EditorView } from "@tiptap/pm/view";
          ╵                            ~~~~~~~~~~~~~~~~~

  You can mark the path "@tiptap/pm/view" as external to exclude it from the bundle, which will
  remove this error.

✘ [ERROR] Could not resolve "@tiptap/pm/state"

    node_modules/@tiptap/suggestion/dist/index.js:2:34:
      2 │ import { Plugin, PluginKey } from "@tiptap/pm/state";
        ╵                                   ~~~~~~~~~~~~~~~~~~

  You can mark the path "@tiptap/pm/state" as external to exclude it from the bundle, which will
  remove this error.

✘ [ERROR] Could not resolve "@tiptap/pm/keymap"

    node_modules/@tiptap/core/dist/index.js:191:23:
      191 │ import { keymap } from "@tiptap/pm/keymap";
          ╵                        ~~~~~~~~~~~~~~~~~~~

  You can mark the path "@tiptap/pm/keymap" as external to exclude it from the bundle, which will
  remove this error.

✘ [ERROR] Could not resolve "@tiptap/pm/view"

    node_modules/@tiptap/suggestion/dist/index.js:3:42:
      3 │ import { Decoration, DecorationSet } from "@tiptap/pm/view";
        ╵                                           ~~~~~~~~~~~~~~~~~

  You can mark the path "@tiptap/pm/view" as external to exclude it from the bundle, which will
  remove this error.

✘ [ERROR] Could not resolve "@tiptap/pm/state"

    node_modules/@tiptap/extension-bubble-menu/dist/index.js:10:34:
      10 │ import { Plugin, PluginKey } from "@tiptap/pm/state";
         ╵                                   ~~~~~~~~~~~~~~~~~~

  You can mark the path "@tiptap/pm/state" as external to exclude it from the bundle, which will
  remove this error.

✘ [ERROR] Could not resolve "@tiptap/pm/model"

    node_modules/@tiptap/core/dist/index.js:344:23:
      344 │ import { Schema } from "@tiptap/pm/model";
          ╵                        ~~~~~~~~~~~~~~~~~~

  You can mark the path "@tiptap/pm/model" as external to exclude it from the bundle, which will
  remove this error.

✘ [ERROR] Could not resolve "@tiptap/pm/state"

    node_modules/@tiptap/extension-floating-menu/dist/index.js:6:34:
      6 │ import { Plugin, PluginKey } from "@tiptap/pm/state";
        ╵                                   ~~~~~~~~~~~~~~~~~~

  You can mark the path "@tiptap/pm/state" as external to exclude it from the bundle, which will
  remove this error.

✘ [ERROR] Could not resolve "@tiptap/pm/transform"

    node_modules/@tiptap/core/dist/index.js:1446:27:
      1446 │ import { liftTarget } from "@tiptap/pm/transform";
           ╵                            ~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@tiptap/pm/transform" as external to exclude it from the bundle, which will
  remove this error.

✘ [ERROR] Could not resolve "@tiptap/pm/commands"

    node_modules/@tiptap/core/dist/index.js:1484:67:
      1484 │ import { createParagraphNear as originalCreateParagraphNear } from "@tiptap/pm/commands";
           ╵                                                                    ~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@tiptap/pm/commands" as external to exclude it from the bundle, which will
  remove this error.

✘ [ERROR] Could not resolve "@tiptap/pm/schema-list"

    node_modules/@tiptap/core/dist/index.js:2029:53:
      2029 │ import { liftListItem as originalLiftListItem } from "@tiptap/pm/schema-list";
           ╵                                                      ~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@tiptap/pm/schema-list" as external to exclude it from the bundle, which
  will remove this error.

✘ [ERROR] Could not resolve "@tiptap/pm/dropcursor"

    node_modules/@tiptap/extension-dropcursor/dist/index.js:3:27:
      3 │ import { dropCursor } from "@tiptap/pm/dropcursor";
        ╵                            ~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@tiptap/pm/dropcursor" as external to exclude it from the bundle, which
  will remove this error.

✘ [ERROR] Could not resolve "@tiptap/pm/history"

    node_modules/@tiptap/extension-history/dist/index.js:3:36:
      3 │ import { history, redo, undo } from "@tiptap/pm/history";
        ╵                                     ~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@tiptap/pm/history" as external to exclude it from the bundle, which will
  remove this error.

✘ [ERROR] Could not resolve "@tiptap/pm/state"

    node_modules/@tiptap/extension-code-block/dist/index.js:3:49:
      3 │ import { Plugin, PluginKey, TextSelection } from "@tiptap/pm/state";
        ╵                                                  ~~~~~~~~~~~~~~~~~~

  You can mark the path "@tiptap/pm/state" as external to exclude it from the bundle, which will
  remove this error.

/home/nexoft/Projects/platform.jounce.ai/node_modules/esbuild/lib/main.js:1575
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 22 errors:
node_modules/@tiptap/core/dist/index.js:152:7: ERROR: Could not resolve "@tiptap/pm/state"
node_modules/@tiptap/core/dist/index.js:153:27: ERROR: Could not resolve "@tiptap/pm/view"
node_modules/@tiptap/core/dist/index.js:191:23: ERROR: Could not resolve "@tiptap/pm/keymap"
node_modules/@tiptap/core/dist/index.js:344:23: ERROR: Could not resolve "@tiptap/pm/model"
node_modules/@tiptap/core/dist/index.js:1446:27: ERROR: Could not resolve "@tiptap/pm/transform"
...
    at failureErrorWithLog (/home/nexoft/Projects/platform.jounce.ai/node_modules/esbuild/lib/main.js:1575:15)
    at /home/nexoft/Projects/platform.jounce.ai/node_modules/esbuild/lib/main.js:1033:28
    at runOnEndCallbacks (/home/nexoft/Projects/platform.jounce.ai/node_modules/esbuild/lib/main.js:1447:61)
    at buildResponseToResult (/home/nexoft/Projects/platform.jounce.ai/node_modules/esbuild/lib/main.js:1031:7)
    at /home/nexoft/Projects/platform.jounce.ai/node_modules/esbuild/lib/main.js:1143:14
    at responseCallbacks.<computed> (/home/nexoft/Projects/platform.jounce.ai/node_modules/esbuild/lib/main.js:680:9)
    at handleIncomingPacket (/home/nexoft/Projects/platform.jounce.ai/node_modules/esbuild/lib/main.js:735:9)
    at Socket.readFromStdout (/home/nexoft/Projects/platform.jounce.ai/node_modules/esbuild/lib/main.js:656:7)
    at Socket.emit (node:events:512:28)
    at addChunk (node:internal/streams/readable:324:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 7,
        file: 'node_modules/@tiptap/core/dist/index.js',
        length: 18,
        line: 152,
        lineText: '} from "@tiptap/pm/state";',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "@tiptap/pm/state" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "@tiptap/pm/state"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 27,
        file: 'node_modules/@tiptap/core/dist/index.js',
        length: 17,
        line: 153,
        lineText: 'import { EditorView } from "@tiptap/pm/view";',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "@tiptap/pm/view" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "@tiptap/pm/view"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 23,
        file: 'node_modules/@tiptap/core/dist/index.js',
        length: 19,
        line: 191,
        lineText: 'import { keymap } from "@tiptap/pm/keymap";',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "@tiptap/pm/keymap" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "@tiptap/pm/keymap"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 23,
        file: 'node_modules/@tiptap/core/dist/index.js',
        length: 18,
        line: 344,
        lineText: 'import { Schema } from "@tiptap/pm/model";',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "@tiptap/pm/model" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "@tiptap/pm/model"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 27,
        file: 'node_modules/@tiptap/core/dist/index.js',
        length: 22,
        line: 1446,
        lineText: 'import { liftTarget } from "@tiptap/pm/transform";',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "@tiptap/pm/transform" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "@tiptap/pm/transform"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 67,
        file: 'node_modules/@tiptap/core/dist/index.js',
        length: 21,
        line: 1484,
        lineText: 'import { createParagraphNear as originalCreateParagraphNear } from "@tiptap/pm/commands";',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "@tiptap/pm/commands" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "@tiptap/pm/commands"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 53,
        file: 'node_modules/@tiptap/core/dist/index.js',
        length: 24,
        line: 2029,
        lineText: 'import { liftListItem as originalLiftListItem } from "@tiptap/pm/schema-list";',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "@tiptap/pm/schema-list" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "@tiptap/pm/schema-list"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 34,
        file: 'node_modules/@tiptap/extension-bubble-menu/dist/index.js',
        length: 18,
        line: 10,
        lineText: 'import { Plugin, PluginKey } from "@tiptap/pm/state";',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "@tiptap/pm/state" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "@tiptap/pm/state"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 49,
        file: 'node_modules/@tiptap/extension-code-block/dist/index.js',
        length: 18,
        line: 3,
        lineText: 'import { Plugin, PluginKey, TextSelection } from "@tiptap/pm/state";',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "@tiptap/pm/state" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "@tiptap/pm/state"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 27,
        file: 'node_modules/@tiptap/extension-dropcursor/dist/index.js',
        length: 23,
        line: 3,
        lineText: 'import { dropCursor } from "@tiptap/pm/dropcursor";',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "@tiptap/pm/dropcursor" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "@tiptap/pm/dropcursor"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 34,
        file: 'node_modules/@tiptap/extension-floating-menu/dist/index.js',
        length: 18,
        line: 6,
        lineText: 'import { Plugin, PluginKey } from "@tiptap/pm/state";',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "@tiptap/pm/state" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "@tiptap/pm/state"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 34,
        file: 'node_modules/@tiptap/extension-focus/dist/index.js',
        length: 18,
        line: 3,
        lineText: 'import { Plugin, PluginKey } from "@tiptap/pm/state";',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "@tiptap/pm/state" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "@tiptap/pm/state"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 42,
        file: 'node_modules/@tiptap/extension-focus/dist/index.js',
        length: 17,
        line: 4,
        lineText: 'import { Decoration, DecorationSet } from "@tiptap/pm/view";',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "@tiptap/pm/view" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "@tiptap/pm/view"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 26,
        file: 'node_modules/@tiptap/extension-gapcursor/dist/index.js',
        length: 22,
        line: 7,
        lineText: 'import { gapCursor } from "@tiptap/pm/gapcursor";',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "@tiptap/pm/gapcursor" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "@tiptap/pm/gapcursor"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 36,
        file: 'node_modules/@tiptap/extension-history/dist/index.js',
        length: 20,
        line: 3,
        lineText: 'import { history, redo, undo } from "@tiptap/pm/history";',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "@tiptap/pm/history" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "@tiptap/pm/history"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 30,
        file: 'node_modules/@tiptap/extension-horizontal-rule/dist/index.js',
        length: 18,
        line: 3,
        lineText: 'import { TextSelection } from "@tiptap/pm/state";',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "@tiptap/pm/state" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "@tiptap/pm/state"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 34,
        file: 'node_modules/@tiptap/extension-link/dist/index.js',
        length: 18,
        line: 12,
        lineText: 'import { Plugin, PluginKey } from "@tiptap/pm/state";',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "@tiptap/pm/state" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "@tiptap/pm/state"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 26,
        file: 'node_modules/@tiptap/extension-mention/dist/index.js',
        length: 18,
        line: 3,
        lineText: 'import { PluginKey } from "@tiptap/pm/state";',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "@tiptap/pm/state" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "@tiptap/pm/state"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 23,
        file: 'node_modules/@tiptap/extension-placeholder/dist/index.js',
        length: 18,
        line: 3,
        lineText: 'import { Plugin } from "@tiptap/pm/state";',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "@tiptap/pm/state" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "@tiptap/pm/state"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 42,
        file: 'node_modules/@tiptap/extension-placeholder/dist/index.js',
        length: 17,
        line: 4,
        lineText: 'import { Decoration, DecorationSet } from "@tiptap/pm/view";',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "@tiptap/pm/view" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "@tiptap/pm/view"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 34,
        file: 'node_modules/@tiptap/suggestion/dist/index.js',
        length: 18,
        line: 2,
        lineText: 'import { Plugin, PluginKey } from "@tiptap/pm/state";',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "@tiptap/pm/state" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "@tiptap/pm/state"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 42,
        file: 'node_modules/@tiptap/suggestion/dist/index.js',
        length: 17,
        line: 3,
        lineText: 'import { Decoration, DecorationSet } from "@tiptap/pm/view";',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "@tiptap/pm/view" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "@tiptap/pm/view"'
    }
  ],
  warnings: []
}
```

### Which browser was this experienced in? Are any special extensions installed?

Any browser, the whole dev environment is broken.

### How can we reproduce the bug on our side?

Just run yarn dev in vite with tiptap ;)

### What did you expect to happen?

At least run in development

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by svenadlung** [comment]
@bigboggy did you install the `@tiptap/pm` package?
(https://tiptap.dev/blog/new-pm-package-and-upgrade-guide-for-beta-210#what-to-do-now)

**Comment by bigboggy** [comment]
@svenadlung yes that solved it for us, funny enough we had it in 208/209 and didn't expect that we need to do that.
