### ISSUE TITLE
Cannot read properties of undefined (reading 'doc')

### ISSUE THREAD

**Issue by HengCC** [ueberdosis/tiptap#3724]
### What’s the bug you are facing?

when use CollaborationCursor extension.  it give the following error , when remove `CollaborationCursor` , it will be ok. 
  
```
TypeError: Cannot read properties of undefined (reading 'doc')
    at createDecorations (mf-dep_vendors-node_modules_tiptap_extension-collaboration-cursor_dist_index_js.19b5fec5.async.js:584:20)
    at Plugin.init (mf-dep_vendors-node_modules_tiptap_extension-collaboration-cursor_dist_index_js.19b5fec5.async.js:638:14)
    at EditorState.reconfigure (mf-dep_vendors-node_modules_prosemirror-state_dist_index_js.76cc35c7.async.js:4466:81)
    at Editor.createView (mf-dep_vendors-node_modules_tiptap_core_dist_index_js.98c93e36.async.js:3636:33)
    at new Editor (mf-dep_vendors-node_modules_tiptap_core_dist_index_js.98c93e36.async.js:3536:10)
    at new Editor (mf-dep_vendors-node_modules_tiptap_react_dist_index_js.fdcbdcaa.async.js:3703:5)
    at mf-dep_vendors-node_modules_tiptap_react_dist_index_js.fdcbdcaa.async.js:4065:22
    at invokePassiveEffectCreate (mf-dep_vendors-node_modules_react-dom_index_js.7bb20710.async.js:23491:20)
    at HTMLUnknownElement.callCallback (mf-dep_vendors-node_modules_react-dom_index_js.7bb20710.async.js:3954:14)
    at Object.invokeGuardedCallbackDev (mf-dep_vendors-node_modules_react-dom_index_js.7bb20710.async.js:4003:16)
    at invokeGuardedCallback (mf-dep_vendors-node_modules_react-dom_index_js.7bb20710.async.js:4065:31)
    at flushPassiveEffectsImpl (mf-dep_vendors-node_modules_react-dom_index_js.7bb20710.async.js:23578:9)
    at unstable_runWithPriority (mf-dep_vendors-node_modules_react-dom_index_js.7bb20710.async.js:27147:12)
    at runWithPriority$1 (mf-dep_vendors-node_modules_react-dom_index_js.7bb20710.async.js:11285:10)
    at flushPassiveEffects (mf-dep_vendors-node_modules_react-dom_index_js.7bb20710.async.js:23451:14)
    at mf-dep_vendors-node_modules_react-dom_index_js.7bb20710.async.js:23328:11
    at workLoop (mf-dep_vendors-node_modules_react-dom_index_js.7bb20710.async.js:27096:34)
    at flushWork (mf-dep_vendors-node_modules_react-dom_index_js.7bb20710.async.js:27069:14)
    at MessagePort.performWorkUntilDeadline (mf-dep_vendors-node_modules_react-dom_index_js.7bb20710.async.js:26836:27) 
```

### Which browser was this experienced in? Are any special extensions installed?

Google Chrome 109.0.5414.119 (x86_64)

### How can we reproduce the bug on our side?

1. hocuspocus --port 1234
2. create front demo 
core code is below . 

```
import Collaboration from '@tiptap/extension-collaboration';
import CollaborationCursor from '@tiptap/extension-collaboration-cursor';
import Document from '@tiptap/extension-document';
import Paragraph from '@tiptap/extension-paragraph';
import Text from '@tiptap/extension-text';
import { EditorContent, useEditor } from '@tiptap/react';
import { HocuspocusProvider } from '@hocuspocus/provider';

import * as Y from 'yjs';

const ydoc = new Y.Doc();

// Set up the Hocuspocus WebSocket provider
const provider = new HocuspocusProvider({
  url: 'ws://127.0.0.1:1234',
  name: 'example-document',
  document: ydoc,
});

export default () => {
  const editor = useEditor({
    extensions: [
      Document,
      Paragraph,
      Text,
      Collaboration.configure({
        document: provider.document,
      }),
      CollaborationCursor.configure({
        provider,
        user: {
          name: 'Cyndi Lauper',
          color: '#f783ac',
        },
      }),
    ],
  });

  return <EditorContent editor={editor} />;
};

```
3. visit editor, it will throw the above exception

### What did you expect to happen?

No error is throw, and the co-cursor can be displayed normally

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by HengCC** [comment]
the related packages version  is below :
```
    "@hocuspocus/provider": "^1.0.1",
    "@tiptap/extension-code-block-lowlight": "^2.0.0-beta.213",
    "@tiptap/extension-collaboration": "^2.0.0-beta.213",
    "@tiptap/extension-collaboration-cursor": "^2.0.0-beta.213",
    "@tiptap/extension-color": "^2.0.0-beta.213",
    "@tiptap/extension-dropcursor": "^2.0.0-beta.213",
    "@tiptap/extension-focus": "^2.0.0-beta.213",
    "@tiptap/extension-font-family": "^2.0.0-beta.213",
    "@tiptap/extension-image": "^2.0.0-beta.213",
    "@tiptap/extension-link": "^2.0.0-beta.213",
    "@tiptap/extension-mention": "^2.0.0-beta.213",
    "@tiptap/extension-subscript": "^2.0.0-beta.213",
    "@tiptap/extension-superscript": "^2.0.0-beta.213",
    "@tiptap/extension-table": "^2.0.0-beta.213",
    "@tiptap/extension-table-cell": "^2.0.0-beta.213",
    "@tiptap/extension-table-header": "^2.0.0-beta.213",
    "@tiptap/extension-table-row": "^2.0.0-beta.213",
    "@tiptap/extension-task-item": "^2.0.0-beta.213",
    "@tiptap/extension-task-list": "^2.0.0-beta.213",
    "@tiptap/extension-text-align": "^2.0.0-beta.213",
    "@tiptap/extension-text-style": "^2.0.0-beta.213",
    "@tiptap/extension-typography": "^2.0.0-beta.213",
    "@tiptap/extension-underline": "^2.0.0-beta.213",
    "@tiptap/pm": "^2.0.0-beta.213",
    "@tiptap/react": "^2.0.0-beta.213",
    "@tiptap/starter-kit": "^2.0.0-beta.213",
    "y-prosemirror": "^1.2.0",
    "y-protocols": "^1.0.5",
    "yjs": "^13.5.45"
```

**Comment by HengCC** [comment]
[disscussion 3038](https://github.com/ueberdosis/tiptap/discussions/3038)  have the same error

**Comment by HengCC** [comment]
And [https://github.com/ueberdosis/tiptap/issues/3039](https://github.com/ueberdosis/tiptap/issues/3039) may be same problem?

**Comment by owynreveon** [comment]
Have you resolved the issue with this [solution](https://github.com/ueberdosis/tiptap/issues/3039#issuecomment-1423290224)? 🤞

**Comment by HengCC** [comment]
@owynreveon  [this release](https://github.com/ueberdosis/tiptap/releases/tag/v2.0.0-beta.214) solved. The root cause is a problem with the build tool.
