### ISSUE TITLE
[Bug]: With prosemirror-view 1.31.0 on doing a `toggleHeading` command with top level NodeView, something breaks and `getPos` throws an exception

### ISSUE THREAD

**Issue by segevfiner** [ueberdosis/tiptap#3999]
### Which packages did you experience the bug in?

core, vue-3

### What Tiptap version are you using?

2.0.3

### What’s the bug you are facing?

With `prosemirror-view` 1.31.0, when doing a `toggleHeading` command with a top level `NodeView` of some kind, the call to `getPos` from the `NodeView` will throw an exception:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'size')
    at NodeViewDesc.posBeforeChild (index.js:714:24)
    at VueNodeView.getPos (index.js:1204:39)
    at Proxy.getPos (VueNodeViewRenderer.ts:82:26)
    at ParagraphView.vue:17:12
    at Proxy.renderFnWithContext (runtime-core.esm-bundler.js:868:19)
    at Proxy.render (NodeViewWrapper.ts:26:30)
    at renderComponentRoot (runtime-core.esm-bundler.js:914:44)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5720:34)
    at ReactiveEffect.run (reactivity.esm-bundler.js:190:25)
    at instance.update (runtime-core.esm-bundler.js:5763:56)
p
```

This seems to be because the descObj in `VueNodeView` is no longer in the children of its `parent` when `getPos` is called i this situation. This might be related to this change in `prosemirror-view`:
```
Improve performance of changing a parent node (by type or attributes) without modifying its children by reusing the DOM of the child nodes.
```

### What browser are you using?

Chrome

### Code example

https://codesandbox.io/p/sandbox/tiptap-paragraph-view-hnsd45

### What did you expect to happen?

For it to work.

### Anything to add? (optional)

This doesn't happen with `prosemirror-view` 1.30.2.

![Recording 2023-04-30 at 18 13 22](https://user-images.githubusercontent.com/24731903/235360851-37643276-c034-43df-b27c-cbdcf21e13fa.gif)

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by tarun-29** [comment]
hey i am facing exact same issue while working with tables i am merging cells and after merging cells i am copying that new merged table and pasting it again in editor and it's showing me the same error below are the screenshots, this is happening because of update attributes in node any help related to this will be very helpful 

<img width="921" alt="Screenshot 2023-08-29 at 12 51 34 AM" src="https://github.com/ueberdosis/tiptap/assets/48859385/4edfc0e7-a790-459c-a3f9-420d21869bed">

<img width="600" alt="Screenshot 2023-08-29 at 12 52 28 AM" src="https://github.com/ueberdosis/tiptap/assets/48859385/2a53af9b-fb74-4abe-8251-32873f575dd9">

**Comment by tarun-29** [comment]
I am using this prosemirror-view version
<img width="576" alt="Screenshot 2023-08-29 at 12 53 19 AM" src="https://github.com/ueberdosis/tiptap/assets/48859385/ea117998-dfb4-4da7-9591-790bb6930cb5">

**Comment by corbinkems** [comment]
I'm getting the same bug with lists. If you copy and paste a list with two or more react node views in them, it throws an error

The call to getPos() that throws the error is in ReactNode.tsx

https://codesandbox.io/p/sandbox/tiptap-getpos-bug-833c66

**Comment by pedro-camaforte** [comment]
2026, and this is not fixed... Facing the same issue... My app is breaking because of this...

**Comment by bdbch** [comment]
Feel free to provide a PR @pedro-camaforte - otherwise I will get back to this when I have all other open issues / prs I'm currently looking into is resolved.
