### ISSUE TITLE
[PRO]: TableOfContent fails with "window is not defined" in Remix.js

### ISSUE THREAD

**Issue by kevlened** [ueberdosis/tiptap#4399]
### Which packages did you experience the bug in?

@tiptap-pro/extension-table-of-content

### What Tiptap version are you using?

@tiptap-pro/extension-table-of-content@^2.2.1, @tiptap-pro/extension-mathematics@^2.2.1, @tiptap/extension-bubble-menu@^2.1.7, @tiptap/extension-color@^2.1.7, @tiptap/extension-placeholder@^2.1.7, @tiptap/extension-text-style@^2.1.7, @tiptap/pm@^2.1.7, @tiptap/react@^2.1.7, @tiptap/starter-kit@^2.1.7

### What’s the bug you are facing?

When trying to load the TableOfContent module in Remix, it fails with:

```
ReferenceError: window is not defined
    at Object.addOptions (/node_modules/@tiptap-pro/extension-table-of-content/dist/index.cjs.js:1:2007)
    at callOrReturn (/node_modules/@tiptap/core/src/utilities/callOrReturn.ts:17:12)
    at new Extension (/node_modules/@tiptap/core/src/Extension.ts:321:22)
    at Function.create (/node_modules/@tiptap/core/src/Extension.ts:337:12)
    at Object.<anonymous> (/node_modules/@tiptap-pro/extension-table-of-content/dist/index.cjs.js:1:1561)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
```

This happens as soon as the module is imported (shown below). While I only tested on Remix, I imagine this effects all SSR frameworks that don't polyfill window.

`import { TableOfContent } from '@tiptap-pro/extension-table-of-content';`

### What browser are you using?

Chrome

### Code example

Because it's a private module, I can't provide a public repro.

### What did you expect to happen?

I expected no failures while loading the module, even if the module isn't used on the server.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by svenadlung** [comment]
Hi @kevlened, thanks for reporting. Working on a fix. Will let you know once it's released.
