### ISSUE TITLE
[Bug]: RangeError: Schema is missing its top node type ('doc')

### ISSUE THREAD

**Issue by rdehuyss** [ueberdosis/tiptap#4419]
### Which packages did you experience the bug in?

core

### What Tiptap version are you using?

2.1.8 (via CDN)

### What’s the bug you are facing?

👋 there!

I'm currently evaluating tiptap and just bumped into the following exception...

I get the following error intermittently in the chrome developer console:
```console
index.js:2246 Uncaught RangeError: Schema is missing its top node type ('doc')
    at l.compile (index.js:2246:19)
    at new G (index.js:2372:35)
    at Pt (getSchemaByResolvedExtensions.ts:190:10)
    at new n (ExtensionManager.ts:34:19)
    at Mt.createExtensionManager (Editor.ts:240:29)
    at new Mt (Editor.ts:79:10)
    at <anonymous>:6:20
```

I'm using [HTMX](https://github.com/bigskysoftware/htmx) and I am thus loading tiptap using the CDN. In some places this error pops up, others not. Once the error is popping up in one place, it is persistent and keeps popping up there. Almost exactly the same code is running fine on a different page. Switching the code from the other page to the page that has the problem does not solve the issue.

This is the code I am using (which is thus fetched by HTMX and contains Bulma css):
```html
<div class="field">
    <div id="editor-textarea" class="textarea">
        <div id="editor" class="content"></div>
    </div>
</div>

<template id="email-html-body">
    <p>This is a test</p>
</template>

<script type="module">
    import {Editor} from 'https://esm.sh/@tiptap/core'
    import StarterKit from 'https://esm.sh/@tiptap/starter-kit'

    const editor = new Editor({
        element: document.querySelector('#editor'),
        modules: [
            StarterKit
        ],
        content: document.querySelector('#email-html-body').innerHTML,
        autofocus: 'start'
    });

    window.editor = editor;
</script>
``` 

### What browser are you using?

Chrome

### What did you expect to happen?

No error

### Anything to add? (optional)

![image](https://github.com/ueberdosis/tiptap/assets/567842/828dd4a3-f854-4ed5-b8c4-c6202a282087)

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by Aerophite** [comment]
I'm using specific extensions as well...but still getting the error.

**Comment by bdbch** [comment]
This is weird. Could you check the extensions or schema on your editor object to see if there is a node called `doc` is included?

**Comment by themre** [comment]
Ah yes,i start with doc type. Let ne know if it works,otherwise I will send you a code snippet later.

**Comment by Aerophite** [comment]
I found the issue (at least when not using the StarterKit). You have to include these extensions.

https://tiptap.dev/docs/editor/api/nodes/document
https://tiptap.dev/docs/editor/api/nodes/text
https://tiptap.dev/docs/editor/api/nodes/paragraph

I couldn't find anywhere in the quick start documentation to support this...but if you look at the migration from v1 to v2 it mentions it there.

https://tiptap.dev/docs/editor/overview/upgrade-guide#explicitly-register-the-document-text-and-paragraph-extensions

**Comment by themre** [comment]
Yeah,adding those is neede if ibuse JSON fornat,but for normal string example starterkit extension is enough.
