### ISSUE TITLE
[Bug]: RangeError: Applying a mismatched transaction on vue-compat

### ISSUE THREAD

**Issue by dermitzos** [ueberdosis/tiptap#4620]
### Which packages did you experience the bug in?

@tiptap/core, @tiptap/vue-3, @tiptap/extension-code-block-lowlight, @tiptap/pm

### What Tiptap version are you using?

2.1.12

### What’s the bug you are facing?

We have created a custom extension extending code-block-lowlight to support our language grammar. In this custom extension we have a ProseMirror plugin that adds a margin-left in the nodes that need it.

```javascript
addProseMirrorPlugins() {
    return [
      ...(this.parent?.() || []),
      new Plugin({
        view: view => {
          return {
            /**
             * This callback is called whenever the state is updated
             */
            update: () => {
              const { doc, tr } = view.state;
              const { initialMargin } = this.options;
              let modified = false;
              // Start with an indentation level of 0
              let nextIndent = 0;
              // Clean up any paragraph margins in paragraphs inside blockquotes
              doc.descendants((node, pos) => {
                if (node.type.name === 'paragraph') {
                  const { parent } = doc.resolve(pos);
                  if (
                    parent.type.name === 'blockquote' &&
                    node.attrs.marginLeft &&
                    node.attrs.marginLeft !== '0px'
                  ) {
                    modified = true;
                    tr.setNodeMarkup(pos, null, { marginLeft: '0px' });
                  }
                  return false;
                }
                return true;
              });
              // Parse each doc child node (block nodes)
              doc.forEach((node, offset, index) => {
                let token = null;
                let currentIndent = nextIndent;
                const { name } = node.type;
                // In case of code block find 1st token
                if (name === 'codeBlock') {
                  [token] = node.textContent.trim().split(' ');
                }
                // Compute the indentation according to the token
                switch (token) {
                  case 'if': {
                    nextIndent += 1;
                    break;
                  }
                  case 'elseif':
                  case 'else': {
                    currentIndent -= 1;
                    break;
                  }
                  case 'endif': {
                    currentIndent -= 1;
                    nextIndent -= 1;
                    break;
                  }
                  default:
                    break;
                }
                // Do not allow for negative indentation
                currentIndent = Math.max(currentIndent, 0);
                // Compute the margin by the indentation
                const marginLeft = `${initialMargin + currentIndent * 20}px`;
                // Set the transaction only on indentation change
                if (
                  node.attrs.marginLeft &&
                  node.attrs.marginLeft !== marginLeft
                ) {
                  modified = true;
                  tr.setNodeMarkup(offset, null, { marginLeft });
                }
              });
              // Dispatch the transaction only if there was a change
              if (modified) {
                view.dispatch(tr);
              }
            },
          };
        },
      }),
    ];
  }
```

We were using tiptap with Vue 2 and we are transitioning our app to Vue 3, currently using vue-compat. Previously the above PM plugin was working correctly, but right now when `view.dispatch(tr)` is called we are getting an error:

```
index.cjs:870 Uncaught RangeError: Applying a mismatched transaction
    at EditorState.applyInner (index.cjs:870:1)
    at EditorState.applyTransaction (index.cjs:818:1)
    at EditorState.apply (index.cjs:794:1)
    at Editor.dispatchTransaction (index.cjs:3645:1)
    at EditorView.dispatch (index.cjs:6008:1)
    at Object.update (custom-code-block-highlight.js:142:22)
    at EditorView.updatePluginViews (index.cjs:5855:1)
    at EditorView.updateStateInner (index.cjs:5802:1)
    at EditorView.updateState (index.cjs:5737:1)
    at Editor.dispatchTransaction (index.cjs:3647:1)
```

Any suggestions on how we can fix it? Maybe this is an issue with vue-compat or should we consider a different approach?

### What browser are you using?

Chrome

### What did you expect to happen?

Dispatch the transaction successfully

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by eybarta** [comment]
Have you found a solution for this?
running into the same issue when testing a simple custom command, i.e:
```
`
const CustomTextAlignExtension = Extension.create({
	name: "customTextAlign",
	addCommands() {
		return {
			setSmartTextAlign:
				(alignment) =>
				({ tr, dispatch, state }) => {
					return this.editor.chain().focus().setTextAlign(alignment).run();
				},
				...
`
```

The function actually works, and currently just returns the call to TextAlign extension - setTextAlign.

However, I get the same error in console:
<img width="896" alt="image" src="https://github.com/ueberdosis/tiptap/assets/12781988/9e015ffe-8f4a-49e0-89e0-0a3a7ee624d8">

**Comment by dermitzos** [comment]
> Have you found a solution for this? running into the same issue when testing a simple custom command, i.e:
> 
> ```
> `
> const CustomTextAlignExtension = Extension.create({
> 	name: "customTextAlign",
> 	addCommands() {
> 		return {
> 			setSmartTextAlign:
> 				(alignment) =>
> 				({ tr, dispatch, state }) => {
> 					return this.editor.chain().focus().setTextAlign(alignment).run();
> 				},
> 				...
> `
> ```
> 
> The function actually works, and currently just returns the call to TextAlign extension - setTextAlign.
> 
> However, I get the same error in console: <img alt="image" width="896" src="https://private-user-images.githubusercontent.com/12781988/299745992-9e015ffe-8f4a-49e0-89e0-0a3a7ee624d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNDM2MDksIm5iZiI6MTcwNjM0MzMwOSwicGF0aCI6Ii8xMjc4MTk4OC8yOTk3NDU5OTItOWUwMTVmZmUtOGY0YS00OWUwLTg5ZTAtMGEzYTdlZTYyNGQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDA4MTUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3NDNmNjQ0ZjllMWE4ZTA5MzUxMzJhMzM2ZjBmOTViYzRkNmUzOWQ0ZWRmYjVlYzA0NDljZmM2OTFhYmQ4ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CrBHSwCFtcUhOr1-voElq0A8W2NnqfOiSdHGS6k32RM">

Are you using vue-compat with your project? Our solution was to rewrite our extension and use tiptap's onUpdate event rather than a custom ProseMirrorPlugin. Not sure if tiptap handles it differently. But this is a too generic error and maybe it's different.

**Comment by eybarta** [comment]
Hi Thanks for your reply.

I'm using 
"vue": "^3.4.15",
"@tiptap/vue-3": "^2.1.16",
"vite": "^4.5.2"

within a Meteor project which I don't think should make a difference.

I'm trying to implement an extension that extends the TextAlign functionality, 
All I need is to do add a custom class to listItems when a BulletList is being text aligned.
This only needs to happened when the user changes text alignment so I think running this on onUpdated is bit overkill.
The error 'mismatched transaction' is very obscure, that's I was sure I'm missing something fairly basic
but just can't figure it out.

**Comment by BrianHung** [comment]
Make sure EditorState is never wrapped in a Vue reactive proxy.
