### ISSUE TITLE
[Bug]: ReferenceError: ClipboardEvent is not defined while testing via react-testing-library

### ISSUE THREAD

**Issue by amit-verma-qatalog** [ueberdosis/tiptap#4673]
### Which packages did you experience the bug in?

core

### What Tiptap version are you using?

2.1.13

### What’s the bug you are facing?

Recently upgrade tiptap deps from 2.0.3 to 2.1.13 and my unit tests are failing because of the ClipboardEvent coming in from `@tiptap/core/src/PasteRule.ts:166:20`

here is the stacktrace from the test: 
```
ReferenceError: ClipboardEvent is not defined

      73 | };
      74 |
    > 75 | const customRender = (ui, options) => render(ui, { wrapper: AllTheProviders, ...options });
         |                                       ^
      76 |
      77 | // re-export everything
      78 | export * from '@testing-library/react';

      at pasteRulesPlugin (../../node_modules/@tiptap/core/src/PasteRule.ts:166:20)
      at ExtensionManager.get plugins [as plugins] (../../node_modules/@tiptap/core/src/ExtensionManager.ts:299:10)
      at Editor.createView (../../node_modules/@tiptap/core/src/Editor.ts:278:38)
      at new Editor (../../node_modules/@tiptap/core/src/Editor.ts:84:10)
      at new Editor (../../node_modules/@tiptap/react/dist/index.cjs:174:5)
      at create (../../node_modules/@tiptap/react/src/useEditor.ts:101:22)
      at apply (../../node_modules/react-dom/cjs/react-dom.development.js:23487:20)
      at HTMLUnknownElement.callCallback (../../node_modules/react-dom/cjs/react-dom.development.js:3945:14)
      at HTMLUnknownElement.callTheUserObjectsOperation (../../node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
      at invokeEventListeners (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLUnknownElementImpl._dispatch (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLUnknownElementImpl.dispatchEvent (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
      at HTMLUnknownElement.dispatchEvent (../../node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
      at Object.apply (../../node_modules/react-dom/cjs/react-dom.development.js:3994:16)
      at invokeGuardedCallback (../../node_modules/react-dom/cjs/react-dom.development.js:4056:31)
      at eventHandler (../../node_modules/react-dom/cjs/react-dom.development.js:23574:9)
      at Scheduler_runWithPriority (../../node_modules/scheduler/cjs/scheduler.development.js:468:12)
      at runWithPriority$1 (../../node_modules/react-dom/cjs/react-dom.development.js:11276:10)
      at flushPassiveEffects (../../node_modules/react-dom/cjs/react-dom.development.js:23447:14)
      at flushWork (../../node_modules/react-dom/cjs/react-dom-test-utils.development.js:992:10)
      at act (../../node_modules/react-dom/cjs/react-dom-test-utils.development.js:1107:9)
      at render (../../node_modules/@testing-library/react/dist/pure.js:97:3)
      at customRender (src/utils/test-utils.js:75:39)
      at Object.<anonymous> (src/mosaiq/components/TextEditor/TextEditor.test.tsx:384:20)
      at TestScheduler.scheduleTests (../../node_modules/react-scripts/node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (../../node_modules/react-scripts/node_modules/@jest/core/build/runJest.js:404:19)
      at _run10000 (../../node_modules/react-scripts/node_modules/@jest/core/build/cli/index.js:320:7)
      at runCLI (../../node_modules/react-scripts/node_modules/@jest/core/build/cli/index.js:173:3)
```

### What browser are you using?

Other

### What did you expect to happen?

expected my tests to pass without this error. It works correctly on the UI. Its just the tests that are failing post the update to `2.1.13`

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by tomo-kn** [comment]
I'm encountering a similar issue where explicitly installing version 2.0.3 of `@tiptap/core` still results in version 2.1.13 being installed as a dependency. This makes it challenging to downgrade the version. 

What would be the recommended approach in this situation? Is temporarily mocking `ClipboardEvent` the only viable solution?

**Comment by ikorason** [comment]
same issue, anyway to work around this?

**Comment by Ihatetomatoes** [comment]
I managed to get round the ClipboardEvent and DragEvent errors by creating `richTextTestUtils.ts`.

```
// richTextTestUtils.ts

export class ClipboardDataMock {
    getData: jest.Mock<string, [string]>;
    setData: jest.Mock<void, [string, string]>;

    constructor() {
        this.getData = jest.fn();
        this.setData = jest.fn();
    }
}

export class ClipboardEventMock extends Event {
    clipboardData: ClipboardDataMock;

    constructor(type: string, options?: EventInit) {
        super(type, options);
        this.clipboardData = new ClipboardDataMock();
    }
}

export class DataTransferMock {
    data: { [key: string]: string };

    constructor() {
        this.data = {};
    }

    setData(format: string, data: string): void {
        this.data[format] = data;
    }

    getData(format: string): string {
        return this.data[format] || '';
    }
}

export class DragEventMock extends Event {
    dataTransfer: DataTransferMock;

    constructor(type: string, options?: EventInit) {
        super(type, options);
        this.dataTransfer = new DataTransferMock();
    }
}
```

Then import it to your test files.

```
// your-component.test.tsx
... all imports

(global as any).ClipboardEvent = ClipboardEventMock;
(global as any).DragEvent = DragEventMock;

...the rest of test file
```

Hope that helps.

**Comment by Ihatetomatoes** [comment]
## Testing onUpdate of TipTap editor
Does anyone have an example how to test the `onUpdate` functionality using `react-testing-library`?

I am having hard time trying to target the **contenteditable** and triggering the change event.

```
<div contenteditable="true" translate="no" class="tiptap ProseMirror" tabindex="0">
    <p><br class="ProseMirror-trailingBreak"></p>
</div>
```

**Comment by ikorason** [comment]
> I managed to get round the ClipboardEvent and DragEvent errors by creating `richTextTestUtils.ts`.
> 
> ```
> // richTextTestUtils.ts
> 
> export class ClipboardDataMock {
>     getData: jest.Mock<string, [string]>;
>     setData: jest.Mock<void, [string, string]>;
> 
>     constructor() {
>         this.getData = jest.fn();
>         this.setData = jest.fn();
>     }
> }
> 
> export class ClipboardEventMock extends Event {
>     clipboardData: ClipboardDataMock;
> 
>     constructor(type: string, options?: EventInit) {
>         super(type, options);
>         this.clipboardData = new ClipboardDataMock();
>     }
> }
> 
> export class DataTransferMock {
>     data: { [key: string]: string };
> 
>     constructor() {
>         this.data = {};
>     }
> 
>     setData(format: string, data: string): void {
>         this.data[format] = data;
>     }
> 
>     getData(format: string): string {
>         return this.data[format] || '';
>     }
> }
> 
> export class DragEventMock extends Event {
>     dataTransfer: DataTransferMock;
> 
>     constructor(type: string, options?: EventInit) {
>         super(type, options);
>         this.dataTransfer = new DataTransferMock();
>     }
> }
> ```
> 
> Then import it to your test files.
> 
> ```
> // your-component.test.tsx
> ... all imports
> 
> (global as any).ClipboardEvent = ClipboardEventMock;
> (global as any).DragEvent = DragEventMock;
> 
> ...the rest of test file
> ```
> 
> Hope that helps.

thank you! this worked like a charm 🫡

**Comment by ThieryMichel** [comment]
FYI, the error did not occur on version 2.1.10, this issue was introduced by version 2.1.11.

**Comment by divmgl** [comment]
> FYI, the error did not occur on version 2.1.10, this issue was introduced by version 2.1.11.

+1, having to downgrade because of this issue. I believe the library has to check if `window` has `ClipboardEvent` rather than referring to it outright.

**Comment by mjabl** [comment]
same issue here

**Comment by allamaley** [comment]
> I managed to get round the ClipboardEvent and DragEvent errors by creating `richTextTestUtils.ts`.
> 
> ```
> // richTextTestUtils.ts
> 
> export class ClipboardDataMock {
>     getData: jest.Mock<string, [string]>;
>     setData: jest.Mock<void, [string, string]>;
> 
>     constructor() {
>         this.getData = jest.fn();
>         this.setData = jest.fn();
>     }
> }
> 
> export class ClipboardEventMock extends Event {
>     clipboardData: ClipboardDataMock;
> 
>     constructor(type: string, options?: EventInit) {
>         super(type, options);
>         this.clipboardData = new ClipboardDataMock();
>     }
> }
> 
> export class DataTransferMock {
>     data: { [key: string]: string };
> 
>     constructor() {
>         this.data = {};
>     }
> 
>     setData(format: string, data: string): void {
>         this.data[format] = data;
>     }
> 
>     getData(format: string): string {
>         return this.data[format] || '';
>     }
> }
> 
> export class DragEventMock extends Event {
>     dataTransfer: DataTransferMock;
> 
>     constructor(type: string, options?: EventInit) {
>         super(type, options);
>         this.dataTransfer = new DataTransferMock();
>     }
> }
> ```
> 
> Then import it to your test files.
> 
> ```
> // your-component.test.tsx
> ... all imports
> 
> (global as any).ClipboardEvent = ClipboardEventMock;
> (global as any).DragEvent = DragEventMock;
> 
> ...the rest of test file
> ```
> 
> Hope that helps.

did someone find a solution? 
If I use the suggested approach, I get a lot of errors from typescript.
I managed to solve some of them and needed to mock way more things, for instance:
```
//my ClipboardEventMock.ts

import { ClipboardDataMock } from './ClipboardDataMock';

export class ClipboardEventMock extends Event {
    clipboardData: ClipboardDataMock;

    constructor(type: string, options?: EventInit) {
        super(type, options);
        this.clipboardData = new ClipboardDataMock();
    }
}
```
```
// DataTransferMock.ts file

const getFileList = () => {
    const dt = new DataTransfer();
    dt.items.add(new File([], 'file.csv'));

    return dt.files;
};

const getDataTransferItemList = () => {
    const dt = new DataTransfer();
    dt.items.add(new File([], 'file.csv'));

    return dt.items;
};

export class DataTransferMock {
    data: { [key: string]: string };

    dropEffect: 'link' | 'none' | 'copy' | 'move' = 'none';

    effectAllowed: 'link' | 'none' | 'copy' | 'move' | 'all' | 'copyLink' | 'copyMove' | 'linkMove' | 'uninitialized' =
        'none';

    files: FileList;

    items: DataTransferItemList;

    types: ReadonlyArray<string>;

    clearData(format?: string): void {
        if (format) {
            delete this.data[format];
        } else {
            this.data = {};
        }
    }

    setDragImage: jest.Mock<void, [Element, number, number]>;

    constructor() {
        this.data = {};
        this.dropEffect = 'move';
        this.effectAllowed = 'all';
        this.files = getFileList();
        this.items = getDataTransferItemList();
        this.types = [];
        this.setDragImage = jest.fn<void, [Element, number, number]>();
    }

    setData(format: string, data: string): void {
        this.data[format] = data;
    }

    getData(format: string): string {
        return this.data[format] || '';
    }
}
```
```
//my DragEventMock.ts file
import { DataTransferMock } from './DataTransferMock';

export class DragEventMock extends Event {
    dataTransfer: DataTransferMock;

    getModifierState: jest.Mock<boolean, [string]>;

    initMouseEvent: jest.Mock<
        void,
        [
            string,
            boolean,
            boolean,
            Window,
            number,
            number,
            number,
            number,
            number,
            boolean,
            boolean,
            boolean,
            boolean,
            number,
            EventTarget | null
        ]
    >;

    initUIEvent: jest.Mock<void, [string, boolean, boolean]>;

    altKey: boolean;

    button: number;

    buttons: number;

    clientX: number;

    bubbles: boolean;

    cancelBubble: boolean;

    cancelable: boolean;

    clientY: number;

    composed: boolean;

    ctrlKey: boolean;

    currentTarget: EventTarget | null;

    defaultPrevented: boolean;

    detail: number;

    eventPhase: number;

    isTrusted: boolean;

    metaKey: boolean;

    movementX: number;

    movementY: number;

    offsetX: number;

    offsetY: number;

    pageX: number;

    pageY: number;

    relatedTarget: EventTarget | null;

    returnValue: boolean;

    screenX: number;

    screenY: number;

    shiftKey: boolean;

    srcElement: EventTarget | null;

    target: EventTarget | null;

    timeStamp: number;

    type: string;

    view: Window | null;

    which: number;

    x: number;

    y: number;

    constructor(type: string, options?: EventInit) {
        super(type, options);
        this.dataTransfer = new DataTransferMock();
        this.altKey = false;
        this.button = 0;
        this.buttons = 0;
        this.clientX = 0;
        this.bubbles = false;
        this.cancelBubble = false;
        this.cancelable = false;
        this.clientY = 0;
        this.composed = false;
        this.ctrlKey = false;
        this.currentTarget = null;
        this.defaultPrevented = false;
        this.detail = 0;
        this.eventPhase = 0;
        this.isTrusted = false;
        this.metaKey = false;
        this.movementX = 0;
        this.movementY = 0;
        this.offsetX = 0;
        this.offsetY = 0;
        this.pageX = 0;
        this.pageY = 0;
        this.relatedTarget = null;
        this.returnValue = false;
        this.screenX = 0;
        this.screenY = 0;
        this.shiftKey = false;
        this.srcElement = null;
        this.target = null;
        this.timeStamp = 0;
        this.type = '';
        this.view = null;
        this.which = 0;
        this.x = 0;
        this.y = 0;
        this.getModifierState = jest.fn<boolean, [string]>();
        this.initUIEvent = jest.fn<void, [string, boolean, boolean]>();

        this.initMouseEvent = jest.fn<
            void,
            [
                string,
                boolean,
                boolean,
                Window,
                number,
                number,
                number,
                number,
                number,
                boolean,
                boolean,
                boolean,
                boolean,
                number,
                EventTarget | null
            ]
        >();
    }
}
```

```
//my ClipboardDataMock.ts
import '@testing-library/jest-dom';

export class ClipboardDataMock {
    getData: jest.Mock<string, [string]>;

    setData: jest.Mock<void, [string, string]>;

    clearData: jest.Mock<void>;

    setDragImage: jest.Mock<void>;

    dropEffect: 'link' | 'none' | 'copy' | 'move' = 'none'; // Align with the expected type

    effectAllowed: 'link' | 'none' | 'copy' | 'move' | 'all' | 'copyLink' | 'copyMove' | 'linkMove' | 'uninitialized' =
        'none';

    types: readonly string[] = []; // Initialize with a default value

    files: FileList = {} as FileList;

    items: DataTransferItemList = {} as DataTransferItemList;

    constructor() {
        this.getData = jest.fn<string, [string]>();
        this.setData = jest.fn<void, [string, string]>();
        this.clearData = jest.fn<void, any, any>();
        this.setDragImage = jest.fn<void, any, any>();
    }
}
```


then I use it in my test file as:

global.ClipboardEvent = ClipboardEventMock;

global.DragEvent = DragEventMock;

But now the error is related to DataTransfer mock
```
   ReferenceError: DataTransfer is not defined

      2 |
      3 | const getFileList = () => {
    > 4 |     const dt = new DataTransfer();
        |                ^
      5 |     dt.items.add(new File([], 'file.csv'));
      6 |
      7 |     return dt.files;
```

did someone find out how to cope with it?

By the way, I also struggle with jest unit testing for TipTap editor as the author of this issue.

**Comment by soren121** [comment]
This should be fixed in 2.2.4!
