### ISSUE TITLE
[Bug]: Running command inside catch block of try/catch throws mismatched transaction error

### ISSUE THREAD

**Issue by Slapbox** [ueberdosis/tiptap#4692]
### Which packages did you experience the bug in?

core

### What Tiptap version are you using?

2.1.13

### What’s the bug you are facing?

This occurs even if you do `editor.commands` instead of `commands`. Usually using `editor.commands` is enough to fix it in edge cases, but not in this case.

### What browser are you using?

Chrome

### What did you expect to happen?

`try/catch`

### Anything to add? (optional)

I tried `commands.first` but it stops if the first command throws an error so it's not suitable either.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by dcourv** [comment]
I couldn't reproduce this. Could you provide a concrete example/code sample?

**Comment by Slapbox** [comment]
Thanks for trying @dcourv. I just gave this a try and apparently it's not very easy to reproduce. Unfortunately the only example I have is some code we can't share publicly.

The only thing I can share is the initial error that we catch. It seems like the initial error must be pretty specific to cause commands run inside of `catch` to complain about mismatched transactions:

```
TypeError: Cannot read properties of undefined (reading 'nodeSize')
    at ResolvedPos.after (index.js:898:1)
    at lift (index.js:996:1)
    at Transaction.lift (index.js:1960:1)
```
