### ISSUE TITLE
[Bug]: No CSP trusted-types support

### ISSUE THREAD

**Issue by MathiasWP** [ueberdosis/tiptap#5650]
### Affected Packages

core

### Version(s)

2.7.2

### Bug Description

Setting [required-trusted-types-for](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/require-trusted-types-for) to `script` and then trying to specify the [trusted-types](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/trusted-types) does not work with tiptap. 

The error thrown is:
```
dom.js:7 
       Uncaught (in promise) TypeError: Failed to execute 'parseFromString' on 'DOMParser': This document requires 'TrustedHTML' assignment.
    at elementFromString (dom.js:7:35)
    at MarkdownParser2.parse (MarkdownParser.js:31:29)
    at Object.onBeforeCreate (Markdown.js:51:75)
    at EventEmitter.ts:29:46
    at Array.forEach (<anonymous>)
    at Editor.emit (EventEmitter.ts:29:17)
    at new Editor (Editor.ts:104:10)
```

And it seems like this this is the culprit:

```ts
export function elementFromString(value) {
    // add a wrapper to preserve leading and trailing whitespace
    const wrappedValue = `<body>${value}</body>`

    return new window.DOMParser().parseFromString(wrappedValue, 'text/html').body
								  ^ This is not possible without trusted-types
}
```

### Browser Used

Chrome

### Expected Behavior

It would be nice to have support for trusted types.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
https://github.com/ueberdosis/tiptap/issues/5559
