### ISSUE TITLE
[Bug]: Uncaught TypeError: Cannot read properties of undefined (reading 'props')  at ReactNodeView.handleSelectionUpdate

### ISSUE THREAD

**Issue by rushillshah** [ueberdosis/tiptap#5870]
### Affected Packages

tiptap/react

### Version(s)

2.9.1

### Bug Description

We are encountering an issue where `this.renderer` is initialized correctly but becomes undefined during certain interactions. This typically occurs when repositioning floating variables in our editor. Occasionally, this issue also arises in production during regular text editing.

This issue appears to be related to a lifecycle problem, where the `renderer` is not properly cleaned up or initialized under specific circumstances. Using null coalescing operators (e.g., `this.renderer?.props?.selected`) in @tiptap/react/dist/index.js:1367 seems to mitigate the issue, but this feels like a workaround rather than a proper solution.

Stacktrace:

```
index.js:1376 Uncaught TypeError: Cannot read properties of undefined (reading 'props')
    at ReactNodeView.handleSelectionUpdate (index.js:1376:1)
    at eval (index.js:159:1)
    at Array.forEach (<anonymous>)
    at Editor.emit (index.js:159:1)
    at Editor.dispatchTransaction (index.js:4601:1)
    at EditorView.dispatch (index.js:5611:1)
    at Object.method [as focus] (index.js:66:1)
    at eval (variable.js:161:1)
    at invokePassiveEffectCreate (react-dom.development.js:23487:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
```

Environment

- Tiptap version: @tiptap/react v2.9.1
-  Prosemirror version: prosemirror-view v1.28.0
-  Node.js version: 20.13.1
-  Browser: Chrome 118.0.5993.89
-  React version: 17.0.2
- Webpack 5.94.0

Steps to Reproduce

	1.	Use @tiptap/react with a custom addNodeView setup, particularly one involving floating elements.
	2.	Interact with floating variables (e.g., reposition or edit them).
	3.	Observe the error during these interactions or general text editing

### Expected Behavior

No TypeError and for the `renderer` to handle intermittent undefined values, or not take undefined values

### Additional Context (Optional)

The issue seems to stem from the ReactNodeView lifecycle. Using null coalescing operators for accessing this.renderer.props.selected appears to resolve the issue temporarily but does not address the root cause.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
Would be ideal to have a codesandbox that reproduces this issue. I agree that adding null checks is not ideal so I would prefer to find the root cause

**Comment by rushillshah** [comment]
Sorry for the delay, setting up a sandbox for reproducing the issue.

**Comment by kongweiying2** [comment]
@rushillshah @nperez0111  I'm facing this exact issue with virtually the same stack trace.

```
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'props')

Source
ReactNodeView.handleSelectionUpdate
node_modules/@tiptap/react/dist/index.js (1376:1)
eval
node_modules/@tiptap/core/dist/index.js (159:1)
Array.forEach
<anonymous>
Editor.emit
node_modules/@tiptap/core/dist/index.js (159:1)
Editor.dispatchTransaction
node_modules/@tiptap/core/dist/index.js (4487:1)
EditorView.dispatch
node_modules/prosemirror-view/dist/index.js (5699:1)
Object.method [as command]
node_modules/@tiptap/core/dist/index.js (66:1)
ReactNodeView.updateAttributes
node_modules/@tiptap/core/dist/index.js (5058:1)
Object.updateAttributes
node_modules/@tiptap/react/dist/index.js (1283:47)
src/view/structure/GroupTipTapExtension.tsx (287:19) @ updateAttributes

  285 |       const updateAttentionTo = (newAttention: number) => {
  286 |           if (props.updateAttributes) {
> 287 |             props.updateAttributes({ attention: newAttention });
      |                   ^
  288 |           } else {
  289 |             console.warn('updateAttributes is not available.');
  290 |           }
Call Stack

```

**Comment by nperez0111** [comment]
Sorry but to help you here, I'd need a repo that is much more minimal than this, way too many things to check

**Comment by rushillshah** [comment]
@kongweiying2 did you manage to resolve the issue? The null coalescing gets rid of the crash for me, but causes some elements from child libraries like `tippy.js` to not show

**Comment by rushillshah** [comment]
Found a solution, creating a PR

**Comment by nperez0111** [comment]
Merged it into develop

**Comment by nperez0111** [comment]
Resolved with version 2.11.1

**Comment by roi1672** [comment]
Hi, I understand this issue is closed, but it seems the @tiptap/vue-3 package might have a similar issue.

**Comment by mclate** [comment]
I'm also facing this issue with @tiptap/vue-3 package...
